// C++ demo for UTF-8-ready routines.
//
// Certain functions in this file comprise machine-generated code and are 
// described as such in the relevant comments.  All other code in this file 
// is copyright 2026 Kirk J Krauss and is a Derivative Work based on material 
// that is copyright 2025 Kirk J Krauss and available at
//
//     https://developforperformance.com/MatchingWildcardsInGoSwiftAndCpp.html
// 
// Licensed under the Apache License, Version 2.0 (the "License"); you may not 
// use this file except in compliance with the License.  You may obtain a copy 
// of the License at
// 
//     https://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the 
// License for the specific language governing permissions and limitations 
// under the License.
//
#if !defined(__cplusplus)
#error "This is a demo program for the FastUtf8 C++ class."
#error "Testcases for the C-style functions in fastutf8.cpp are available."
#error "See testutf8.cpp and its documentation."
#endif

#if defined(_WIN32)
#include <windows.h>      // For SetConsoleOutputCP()
#endif  // _WIN32

#include <iostream>
#include <cstdio>
#include <cstring>
#include <string>
#include <cmath>
#include <chrono>
#include "fastutf8.h"
using namespace FastUtf8;

// The code within the following function, along with the "AI Overview" text, 
// was generated by Google on April 16, 2026, in response to the query:
//
//   std::string demo with concatenate, separate, substring, whole string 
//   comparison, and substring find operations
//
// AI Overview
// This C++ demo demonstrates fundamental std::string operations: 
// concatenation (+, append), substring extraction (substr), finding 
// substrings (find, npos), and comparison (==). std::string provides 
// efficient, high-level text manipulation, with find() returning the index 
// of the first occurrence or std::string::npos if not found.
//
int AsciiStdStringDemo(void)
{
   // 1. Creation and Concatenation
   std::string s1 = (const char *) "Hello";
   std::string s2 = "World";
   // Using + operator
   std::string s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   // Using append()
   s3.append(" Welcome."); // "Hello, World! Welcome."

   std::cout << "Concatenated: " << s3 << std::endl;

   // 2. Substring (Position, Length)
   // Extract "World"
   std::string sub = s3.substr(7, 5);
   std::cout << "Substring: " << sub << std::endl;

   // 3. Substring Find
   size_t found = s3.find("Welcome");
   if (found != std::string::npos) {
       std::cout << "'Welcome' found at: " << found << std::endl;
   }

   // 4. Whole String Comparison
   std::string s4 = "Hello, World! Welcome.";
   if (s3 == s4) {
       std::cout << "Strings are equal." << std::endl;
   }

   // 5. Separate (Splitting by character)
   size_t commaPos = s3.find(',');
   if (commaPos != std::string::npos) {
       std::string firstPart = s3.substr(0, commaPos);
       std::string secondPart = s3.substr(commaPos + 2); // Skip ", "
       std::cout << "Separated: '" << firstPart << "' and '" << secondPart << "'" << std::endl;
   }

   return 0;
}

// The code within the following function is based on the above machine-
// generated code but is modified to work with the FastUtf8::Uniseries class 
// in the place of std::string.  Inline comments are modified accordingly.
//
int AsciiUniseriesDemo(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   std::cout << "Concatenated: " << s3 << std::endl;

   // 2. Substring (Position, Length)
   // Extract "World"
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);
   std::cout << "Substring: " << sub << std::endl;

   // 3. Substring Find
   int iFound = s3.find("Welcome");

   if (iFound != -1)
   {
      std::cout << "'Welcome' found at: " << iFound << std::endl;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 == s4)
   {
      std::cout << "Strings are equal." << std::endl;
   }

   // 5. Separate (Splitting by character)
   int iCommaPos = s3.find(',');

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "
      std::cout << "Separated: '" << sFirstPart << "' and '" << sSecondPart << "'" << std::endl;
   }

   return 0;
}

// This code is similar to the above AsciiUniseriesDemo() code but with 
// Japanese content.  To build it with the Microsoft compiler, use the /utf-8 
// switch for best content display.  The (N)SimSun or MS Gothic fonts include 
// the necessary ideographs.
//
int Utf8UniseriesDemo(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "こんにちは";
   Uniseries s2 = "は世界";
   // Using + operator
   Uniseries s3 = s1 + "、" + s2 + "！"; // "Hello, World!"
   s3 = s3 + " いらっしゃいませ。"; // "Hello, World! Welcome."

   std::cout << "Concatenated (連結済み)： " << s3 << std::endl;

   // 2. Substring (Position, Length)
   // Extract "World"
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 12);
   std::cout << "Substring (部分文字列)： " << sub << std::endl;

   // 3. Substring Find
   int iFound = s3.find("いらっしゃいませ");

   if (iFound != -1)
   {
      std::cout << "\"いらっしゃいませ\" found at (発見場所)： " << iFound << std::endl;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "こんにちは、は世界！ いらっしゃいませ。";

   if (s3 == s4)
   {
      std::cout << "Strings are equal (文字列は等しい)。" << std::endl;
   }

   // 5. Separate (Splitting by code point)
   int iCommaPos = s3.find("、");

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "
      std::cout << "Separated (分離済み)： \"" << sFirstPart << "\" and \"" << 
         sSecondPart << "\"" << std::endl;
   }

   return 0;
}

// This code is similar to the machine-generated std::string demo, but it 
// sends no output to the console.
int AsciiStdStringMute()
{
   // 1. Creation and Concatenation
   std::string s1 = "Hello";
   std::string s2 = "World";
   // Using + operator
   std::string s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   // Using append()
   s3.append(" Welcome."); // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World"
   std::string sub = s3.substr(7, 5);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   size_t found = s3.find("Welcome");

   if (found == std::string::npos)
   {
      return 1;
   }

   // 4. Whole String Comparison
   std::string s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   size_t commaPos = s3.find(',');
   if (commaPos != std::string::npos)
   {
      std::string firstPart = s3.substr(0, commaPos);
      std::string secondPart = s3.substr(commaPos + 2); // Skip ", "

      if (firstPart == secondPart)
      {
         return 1;
      }
   }

   return 0;
}

// This code is similar to the FastUtf8::Uniseries ASCII demo, but it sends no 
// output to the console.
int AsciiUniseriesMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   int iFound = s3.find("Welcome");

   if (iFound == -1)
   {
      return 1;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   int iCommaPos = s3.find(',');

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "

      if (sFirstPart == sSecondPart)
      {
         return 1;
      }
   }

   return 0;
}

// This is the same as the above function, except that it calls pSeparate() in 
// place of find().
int AsciiUniseriesSeparateMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   int iFound = s3.find("Welcome");

   if (iFound == -1)
   {
      return 1;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   std::unique_ptr<FastUtf8::Uniseries> psFirstPart = s3.pSeparate(',');

   if (*psFirstPart == s3)
   {
      return 1;   // "Hello" != " World! Welcome."
   }

   return 0;
}

// This is the same as the above function, except that it calls pFind() in 
// place of find().
int AsciiUniseriespFindMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   uint8_t *pFound = s3.pFind("Welcome");

   if (!pFound)
   {
      return 1;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   uint8_t *pFirstPart = s3.pFind(',');

   if (!std::strcmp(
         reinterpret_cast<char *> (const_cast<uint8_t *> (pFirstPart)), 
         reinterpret_cast<char *> (const_cast<uint8_t *> (s3.getContent()))))
   {
      return 1;   // "Hello" != " World! Welcome."
   }

   return 0;
}

// This code is similar to the FastUtf8::Uniseries Japanese demo above, but it 
// sends no output to the console.
int Utf8UniseriesMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "こんにちは";
   Uniseries s2 = "は世界";
   // Using + operator
   Uniseries s3 = s1 + "、" + s2 + "！"; // "Hello, World!"
   s3 = s3 + " いらっしゃいませ。"; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }
   
   // 3. Substring Find
   int iFound = s3.find("いらっしゃいませ");

   if (iFound == -1)
   {
      return 1;
   }
   
   // 4. Whole String Comparison
   Uniseries s4 = "こんにちは、は世界！ いらっしゃいませ。";

   if (s3 != s4)
   {
      return 1;
   }
   
   // 5. Separate (Splitting by code point)
   int iCommaPos = s3.find("、");

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "

      if (sFirstPart == sSecondPart)
      {
         return 1;
      }
   }
   
   return 0;
}

#include <sstream>

// Returns true if the query content includes Japanese code points, and false 
// if it doesn't.
bool ContainsJapanese(FastUtf8::Uniseries sQuery)
{
   bool bRetVal = false;

   for (FastUtf8::Uniseries::Iterator itr = sQuery.begin(); 
                      itr != sQuery.end(); ++itr)
   {
      uint32_t n = *itr;                       // UTF-8 code point in sQuery

      if ((n >= 0xE38180 && n <= 0xE383BF) ||  // Hiragana/Katakana range
          (n >= 0xE4B880 && n <= 0xE9BFBF) ||  // CJK unified ideographs
          (n >= 0xEFBDA5 && n <= 0xEFBE9F))    // Shift-JIS encodings
      {
         bRetVal = true;
      }
   }

   return bRetVal;
}

int UniseriesIteratorDemo(void)
{
   FastUtf8::Uniseries sEnglish = u8"Mr. Roboto says domo arigato.";
   FastUtf8::Uniseries sMixed = u8"Mr. Roboto says どうもありがとうございます。";

   if (!ContainsJapanese(sEnglish))
   {
      std::cout << std::endl << "    This content..." << std::endl << 
                      "        " << sEnglish;
      std::cout << std::endl << "    ...includes no Japanese code points." << 
                      std::endl;
   }

   if (ContainsJapanese(sMixed))
   {
      std::cout << std::endl << "    This content..." << std::endl << 
                      "        " << sMixed;
      std::cout << std::endl << "    ...includes Japanese code points." << 
                      std::endl;
   }

   return 0;
}

int UniseriespFindTokenDemo(void)
{
   // Define a pair of short Japanese buns and equivalent English sentences, 
   // plus a mix of the two.
   FastUtf8::Uniseries sJapanesePart1 = u8"これがミスター・ロボットに秘密を話すとこうなるんだ。 ";
   FastUtf8::Uniseries sEnglishPart1 = 
      u8"This is what happens when you tell Mr Roboto a secret. ";
   FastUtf8::Uniseries sJapanesePart2 = u8"ミスター・ロボットがどうもありがとうと言っています。 ";
   FastUtf8::Uniseries sEnglishPart2 = u8"Mr Roboto says domo arigato.";
   FastUtf8::Uniseries sMixedPart2 = u8"Mr Roboto says どうもありがとうございます。";

   // Combine uniseries in the two languages.
   FastUtf8::Uniseries sJapaneseSentences = sJapanesePart1 + sJapanesePart2;
   FastUtf8::Uniseries sEnglishSentences = sEnglishPart1 + sEnglishPart2;
   FastUtf8::Uniseries sMixedSentences = sJapanesePart1 + sMixedPart2;

   // Define a token set with both the Latin period (.) and Japanese kuten (。).
   FastUtf8::Uniseries sKutenSet = u8"。.";

   // Define a search pattern with a space followed by a wildcard.
   FastUtf8::Uniseries sSearchPattern = u8" *";

   // Extract the second portion of the combined Japanese bun.
   uint8_t *puzKuten = sJapaneseSentences.pFindToken(sKutenSet);
   uint8_t *puzFirst = sJapaneseSentences.pFindWild(sSearchPattern, &puzKuten);
   uint8_t *puzLast = sJapaneseSentences.pFindToken(puzFirst, sKutenSet);
   FastUtf8::Uniseries sJapanesePart2a(puzFirst, puzLast);

   std::cout << std::endl << "    From this combined content..." << 
                      std::endl << "        " << sJapanesePart1 << 
                      sJapanesePart2;
   std::cout << std::endl << "    ...extracted the second portion:" << 
                      std::endl <<"        " << sJapanesePart2a << std::endl;

   // Extract the second portion of the combined English sentences.
   puzKuten = sEnglishSentences.pFindToken(sKutenSet);
   puzFirst = sEnglishSentences.pFindWild(sSearchPattern, &puzKuten);
   puzLast = sEnglishSentences.pFindToken(puzFirst, sKutenSet);
   FastUtf8::Uniseries sEnglishPart2a(puzFirst, puzLast);

   std::cout << std::endl << "    From this combined content..." << 
                      std::endl << "        " << sEnglishPart1 << 
                      sEnglishPart2;
   std::cout << std::endl << "    ...extracted the second portion:" << 
                      std::endl <<"        " << sEnglishPart2a << std::endl;

   // Extract the second portion of the mixed combination.
   puzKuten = sMixedSentences.pFindToken(sKutenSet);
   puzFirst = sMixedSentences.pFindWild(sSearchPattern, &puzKuten);
   puzLast = sMixedSentences.pFindToken(puzFirst, sKutenSet);
   FastUtf8::Uniseries sMixedPart2a(puzFirst, puzLast);

   std::cout << std::endl << "    From this combined content..." << 
                      std::endl << "        " << sMixedSentences;
   std::cout << std::endl << "    ...extracted the second portion:" << 
                      std::endl << "        " << sMixedPart2a << std::endl;

   return 0;
}

int AsciiPerformanceDemo(int iReps)
{
   const double fBase = 10.0;
   const double fExpNanoseconds = 9.0;
   const double fExpMilliseconds = 3.0;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeStart;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeFinish;
   uint64_t     uTime;
   double       fTime;
   float        fTimeInSeconds;
   int          nReps = iReps;

   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiStdStringMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "std::string (ASCII) demo, with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);
   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiUniseriesMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries ASCII muted demo, with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);
   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiUniseriesSeparateMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                         timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) / pow(fBase, fExpNanoseconds)) * 
                             pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries ASCII using pSeparate() in place of find(), with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);
   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (Utf8UniseriesMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) / pow(fBase, fExpNanoseconds)) * 
                      pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries UTF-8 demo, with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);

   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiUniseriespFindMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) / pow(fBase, fExpNanoseconds)) * 
                      pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries ASCII using pFind() in place of find(), with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);


   return 0;
}

// Demonstration of parsing a buffer containing MLA references (author, title, 
// publisher, date).  Includes performance comparisons for two functions, one 
// based on std::string and generated in response to a Google query, and the 
// other based on FastUtf8::Uniseries.
//
#include <vector>
#include <sstream>
#include <algorithm>
#include <cctype>

// The code within the following two functions, along with the "AI Overview" 
// text, was generated by Google on May 2, 2026, in response to the query:
//
//   code a c++ function that accepts two buffers declared as char *, where 
//   one buffer comprises an author's last name, and the other buffer 
//   comprises a list of MLA references for individual authors, and where the 
//   function finds any first matching author among the references, so that 
//   for all list entries matching that author, the function creates a 
//   std::string comprising the author's first name, last name, and a list of 
//   titles among the MLA references, where the initial last name matching is 
//   case-insensitive
//
// AI Overview
// This C++ function processes two char* buffers—one containing a target last 
// name and the other a newline-separated list of MLA citations—to identify a 
// matching author, case-insensitively, and extracts their titles into a 
// formatted std::string. 
//
// Helper to make a string lowercase for case-insensitive comparison
std::string toLower(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c){ return std::tolower(c); });
    return s;
}

std::string FetchTitlesByAuthorUsingStdString(char* targetLastName, char* mlaReferences) {
    std::string targetName(targetLastName);
    std::string references(mlaReferences);
    std::string lowerTarget = toLower(targetName);
    
    std::stringstream ss(references);
    std::string line;
    std::string authorFullName = "";
    std::vector<std::string> titles;
    
    // Parse through references
    while (std::getline(ss, line)) {
        if (line.empty()) continue;

        // Simple MLA detection: "Lastname, Firstname." or similar
        size_t commaPos = line.find(',');
        if (commaPos != std::string::npos) {
            std::string lastName = line.substr(0, commaPos);
            
            // Case-insensitive match on last name
            if (toLower(lastName) == lowerTarget) {
                // Extract author full name on first match
                if (authorFullName.empty()) {
                    // Extract until the end of the first name, assuming "Last, First."
                    size_t periodPos = line.find('.', commaPos);
                    authorFullName = line.substr(0, periodPos + 1);
                }
                
                // Extract title (assuming it's after comma and inside italics or quotes)
                // This is a naive extraction focusing on MLA 8+ "Title."
                size_t firstPeriod = line.find('.');
                size_t secondPeriod = line.find('.', firstPeriod + 1);
                if (secondPeriod != std::string::npos) {
                    // Assume title is between first and second period
                    std::string title = line.substr(firstPeriod + 2, secondPeriod - (firstPeriod + 1));
                    titles.push_back(title);
                }
            }
        }
    }
    
    // Format output
    if (authorFullName.empty()) return "Author not found.";
    
    std::string result = "Author: " + authorFullName + "\nTitles:\n";
    for (const auto& title : titles) {
        result += "- " + title + "\n";
    }
    
    return result;
}

// Given an author's last name, performs a case-insensitive search and 
// extracts a list of titles corresponding to the full name for any first 
// match.
//
FastUtf8::Uniseries FetchTitlesByAuthorUsingFastUtf8Uniseries(
                      uint8_t *puzAuthorLastname, uint8_t *puzReferences)
{
   FastUtf8::Uniseries sReferences(puzReferences);
   FastUtf8::Uniseries sAuthorMatch(puzAuthorLastname);
   FastUtf8::Uniseries sTitles;
   uint8_t *puzTitle;

   // Search on the author's last name concatenated with comma. 
   // This ensures that (for example) "mccullers" won't match "mccullerson".
   sAuthorMatch += ",";
   uint8_t *puzFinding = sReferences.casepFind(sAuthorMatch);

   if (puzFinding)
   {
      // Got a match.  This call to pSeparate() places a null terminator 
	  // into the sReferences content buffer, in place of the "." that follows 
      // the author's full name, so that full name becomes a null-terminated 
	  // series of code points.
      uint8_t *puzAuthorName = sReferences.pSeparate(&puzFinding, ".");
	  FastUtf8::Uniseries sAuthorName(puzAuthorName);
	  sAuthorMatch = puzAuthorName;

      // This call to pSeparate() places a null terminator in place of the "." 
	  // that following the title (from the same line as the author's name).
	  // The bTrim flag elides any white space around the returned series.
      std::unique_ptr<FastUtf8::Uniseries> psAuthorSurname = 
                      sAuthorName.pSeparate(",", /* bTrim = */ true);

      // Piece together a heading line, such as "Titles by Carson McCullers:".
      sTitles = "Titles by";
      sTitles += sAuthorName;
      sTitles += " ";
      sTitles += *psAuthorSurname;

      // Piece together a title line, such as "- The Heart Is a Lonely Hunter."
      sTitles += ":\n- ";
      puzTitle = sReferences.pSeparate(&puzFinding, ".", /* bTrim = */ true);
      sTitles += puzTitle;
      sTitles += ".\n";

      do
      {
         // Search on the author's full name in the form that we've first 
		 // found it in the references.
         puzFinding = sReferences.casepFind(sAuthorMatch, puzFinding);

         if (!puzFinding)
         {
      	    break;  // No more matches.
         }

         // The next title should begin right after the next ". " sequence.
         puzFinding = sReferences.pFind(".", puzFinding);
         ++puzFinding;

         // This call to pSeparate() places a null terminator into the 
		 // sReferences content buffer, in place of the "." that follows the 
         // title.  The bTrim flag elides any white space around the title 
         // but does not affect the remaining sReferences content. 
         puzTitle = sReferences.pSeparate(&puzFinding, ".", /* bTrim = */ true);

         // Piece together a title line, such as "- Clock Without Hands.", 
		 // based on the null-terminated content, i.e., with minimal Uniseries 
		 // construction.
         sTitles += "- ";
         sTitles += puzTitle;
         sTitles += ".\n";
      } while (true);
   }
   else
   {
      sTitles = "No match found for ";
	  sTitles += puzAuthorLastname;
   }

   return sTitles;
}

// Invokes one of the above two MLA-title-extraction functions for ASCII text. 
// Invokes the FastUtf8-based function for a version of the same text in Greek 
// and in Georgian.  Optionally reruns the functions a bunch of times to 
// capture and display performance outcomes.
//
int TimeTitlesByAuthor(char *pszReferences, char *pszAuthorLastName, 
                       char *pszCodePointSet, int iReps, bool bUseStdString)
{
   const double fBase = 10.0;
   const double fExpNanoseconds = 9.0;
   const double fExpMilliseconds = 3.0;

   std::chrono::time_point<std::chrono::high_resolution_clock> timeStart;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeFinish;
   uint64_t uTime;          // Duration from std::chrono.
   double fTime;            // Timing represented in nanoseconds.
   float  fTimeInSeconds;   // Timing represented in seconds.
   int    nReps = iReps;

   std::cout << std::endl;
   std::cout << "    From list of references..." << std::endl;
   std::cout << pszReferences << std::endl << std::endl;

   if (bUseStdString)
   {
      // Get and display output using the function based on std::string.
      std::string strTitles = FetchTitlesByAuthorUsingStdString(
                      pszAuthorLastName, pszReferences);
      std::cout << std::endl << 
           "    ...extracted titles specified by author: " << 
                      pszAuthorLastName << "..." << std::endl;
      std::cout << strTitles  << "    ...using std::string." << 
                      std::endl << std::endl;

      // Rerun the std:string-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         strTitles = FetchTitlesByAuthorUsingStdString(
                      pszAuthorLastName, pszReferences);
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Represent the std:string-based function's timing in seconds, to 
      // millisecond precision.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "std::string (%s) demo time, with %d reps:\n     %.3f seconds\n", 
                      pszCodePointSet, iReps, fTimeInSeconds);
   }
   else
   {
      // Get and display output from the function based on FastUtf8::Uniseries.
      FastUtf8::Uniseries sTitles = FetchTitlesByAuthorUsingFastUtf8Uniseries(
                      reinterpret_cast<uint8_t *> (pszAuthorLastName), 
                      reinterpret_cast<uint8_t *> (pszReferences));

      std::cout << std::endl << 
           "    ...extracted titles specified by author: " << 
                   pszAuthorLastName << "..." << std::endl;
      std::cout << sTitles << "    ...using FastUtf8::Uniseries." 
                      << std::endl << std::endl;

      // Rerun the FastUtf8::Uniseries-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         sTitles = FetchTitlesByAuthorUsingFastUtf8Uniseries(
                         reinterpret_cast<uint8_t *> (pszAuthorLastName), 
                         reinterpret_cast<uint8_t *> (pszReferences));
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Display the FastUtf8::Uniseries-based function's timing.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                         timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                         pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "FastUtf8::Uniseries (%s) demo time, with %d reps:\n     %.3f seconds\n", 
                         pszCodePointSet, iReps, fTimeInSeconds);
   }

   return 0;
}

// Drives display of content search and token-based separation functionality 
// of FastUtf8::Uniseries, and provides a performance comparison with 
// std::string.  Declares and initializes MLA-style lists of literary 
// references, in Latin text and in Greek and Adlam script.  Passes these, 
// along with one of the authors' lowercased last names, to a function that 
// gets output and timing results for MLA-title-extraction functions for 
// console display.
//
int FetchTitlesByAuthor(int iReps)
{
   // This is a list of MLA-style literary references.
   char szReferencesAscii[900] = "\
Capote, Truman. Breakfast at Tiffany's: A Short Novel and Three Stories. Random House, 1958.\n\
Capote, Truman. In Cold Blood. Random House, 1965.\n\
Capote, Truman. Other Voices, Other Rooms. Random House, 1948.\n\
Hellman, Lillian. The Children's Hour. 1934. Famous American Plays of the 1930s, edited by Harold Clurman, Dell, 1959.\n\
Hellman, Lillian. Toys in the Attic: A New Play. Random House, 1960.\n\
McCullers, Carson. The Heart Is a Lonely Hunter. Houghton Mifflin, 1940.\n\
McCullers, Carson. The Member of the Wedding. Houghton Mifflin, 1946.\n\
McCullers, Carson. Clock Without Hands. Houghton Mifflin, 1961.\n\
Williams, Tennessee. The Glass Menagerie. Tennessee Williams: Plays 1937 through 1955, edited by Mel Gussow and Kenneth Holditch, Library of America, 2000, pp. 217-331.\n\
Williams, Tennessee. \"The Night of the Iguana.\" Three by Tennessee, edited by Darvin Kane, Signet, 1976, pp. 1-122.";
   char szAuthorLastnameAscii[10] = "mccullers";
   char szCodePointSetAscii[6] = "ASCII";

   // This is a Greek transliteration of the above references.
   char szReferencesGreek[2614] = "\
Καπότε, Τρούμαν. Πρωινό στο Tiffany's: Ένα σύντομο μυθιστόρημα και τρεις ιστορίες. Random House, 1958.\n\
Καπότε, Τρούμαν. Στο Ψυχρό Αίμα. Random House, 1965.\n\
Καπότε, Τρούμαν. Άλλες Φωνές, Άλλα Δωμάτια. Random House, 1948.\n\
Χέλμαν, Λίλιαν. Η Ώρα των Παιδιών. 1934. Διάσημα Αμερικανικά Θεατρικά Έργα της δεκαετίας του 1930, επιμέλεια Χάρολντ Κλούρμαν, Ντελ, 1959.\n\
Χέλμαν, Λίλιαν. Παιχνίδια στη Σοφίτα: Ένα Νέο Παιχνίδι. Random House, 1960.\n\
ΜακΚάλερς, Κάρσον. Η Καρδιά Είναι Ένας Μοναχικός Κυνηγός. Χάουτον Μίφλιν, 1940.\n\
ΜακΚάλερς, Κάρσον. Το Μέλος του Γάμου. Χάουτον Μίφλιν, 1946.\n\
ΜακΚάλερς, Κάρσον. Ρολόι χωρίς χέρια. Χάουτον Μίφλιν, 1961.\n\
Ουίλιαμς, Τενεσί. Το Γυάλινο Ζωολογικό Κήπο. Ουίλιαμς, Τενεσί: Θεατρικά έργα 1937 έως 1955, επιμέλεια Μελ Γκούσοου και Κένεθ Χόλντιτς, Βιβλιοθήκη της Αμερικής, 2000, pp. 217-331.\n\
Ουίλιαμς, Τενεσί. \"Η Νύχτα της Ιγκουάνα.\" Τρία από τον Τενεσί, επιμέλεια Ντάρβιν Κέιν, Σφραγιδόλιθος, 1976, pp. 1-122.";
   char szAuthorLastnameGreek[28] = "μακκάλερς";
   char szCodePointSetGreek[6] = "Greek";

   // This translation of the references is mostly in Georgian. Some Latin 
   // letters with strokes are mixed in for case-insensitive matching.
   char szReferencesMixed[3585] = "\
კაპოტე, Ⱦრუმენი. საუზმე ტიფანისთან: მოკლე რომანი და სამი მოთხრობა. რენდომ ჰაუსი, 1958.\n\
კაპოტე, Ⱦრუმენი. ცივსისხლიანად. რენდომ ჰაუსი, 1965.\n\
კაპოტე, Ⱦრუმენი. სხვა ხმები, სხვა ოთახები. რენდომ ჰაუსი, 1948.\n\
ჰელმანი, ლილიანი. ბავშვთა საათი. 1934. 1930-იანი წლების ცნობილი ამერიკული პიესები, რედაქტორი ჰაროლდ კლურმანი, დელის, 1959.\n\
ჰელმანი, ლილიანი. სათამაშოები სხვენში: ახალი თამაში. რენდომ ჰაუსი, 1960.\n\
მȺკკალერსი, კȺრსონი. გული მარტოსული მონადირეა. ჰოტონ მიფლინი, 1940.\n\
მȺკკალერსი, კȺრსონი. ქორწილის წევრი. ჰოტონ მიფლინი, 1946.\n\
მȺკკალერსი, კȺრსონი. საათი ხელების გარეშე. ჰოტონ მიფლინი, 1961.\n\
უილიამსი, Ⱦენესი. შუშის ზოოპარკი. ტენესი უილიამსი: პიესები 1937 წლიდან 1955 წლამდე, რედაქტორები მელ გასოუ და კენეტ ჰოლდიჩი, ამერიკის ბიბლიოთეკა, 2000, გვ. 217-331.\n\
უილიამსი, Ⱦენესი. \"იგუანას ღამე.\" „სამი ტენესის მიერ“, რედაქტორი დარვინ კეინი, ხელმოწერა, 1976, გვ. 1-122.";
   char szAuthorLastnameMixed[41] = "მⱥკკალერსი";
   char szCodePointSetMixed[15] = "mixed Georgian";

   // These calls pass the references and author last names to the functions 
   // that perform the search.  They also accumulate the associated timings 
   // for multiple quiet repetitions.  They display all results at the console.
   TimeTitlesByAuthor(szReferencesAscii, szAuthorLastnameAscii, 
                      szCodePointSetAscii, iReps, /* bUseStdString = */ true);
   TimeTitlesByAuthor(szReferencesAscii, szAuthorLastnameAscii, 
                      szCodePointSetAscii, iReps, /* bUseStdString = */ false);
   TimeTitlesByAuthor(szReferencesGreek, szAuthorLastnameGreek, 
                      szCodePointSetGreek, iReps, /* bUseStdString = */ false);
   TimeTitlesByAuthor(szReferencesMixed, szAuthorLastnameMixed, 
                      szCodePointSetMixed, iReps, /* bUseStdString = */ false);
   return 0;
}

// The code within the following two functions, along with the "AI Overview" 
// text, was generated by Google on May 7, 2026, in response to the query:
//
//   code a c++ function that accepts two buffers declared as char *, where 
//   one buffer comprises a title, and the other buffer comprises a list of 
//   MLA references for individual authors, and where the function finds any 
//   first matching title among the references, so that for a first list entry 
//   matching that title, the function creates a std::string comprising the 
//   author's name, where the initial title matching is case-insensitive
//
// AI Overview
// This C++ function searches for a case-insensitive title match within a 
// newline-separated list of MLA references. It uses std::string for robust 
// text handling, converting both the search title and references to lowercase 
// using std::tolower for comparison, then extracts the author name.

#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>
#include <cctype>

// Function to find author by title (case-insensitive)
std::string FetchAuthorByTitleUsingStdString(char* targetTitle, char* mlaReferences) {
    if (!targetTitle || !mlaReferences) return "";

    std::string searchTitle = toLower(std::string(targetTitle));
    std::string references(mlaReferences);
    std::stringstream ss(references);
    std::string line;

    // Process each reference entry line-by-line
    while (std::getline(ss, line)) {
        if (line.empty()) continue;

        // Assumes MLA format: Author(s). "Title." Journal...
        // Extract title part (assuming it's between first and second '.')
        size_t firstDot = line.find('.');
        size_t secondDot = line.find('.', firstDot + 1);
        
        if (firstDot != std::string::npos && secondDot != std::string::npos) {
            std::string currentTitle = line.substr(firstDot + 2, secondDot - firstDot - 2);
            
            // Remove leading/trailing quotes if necessary
            currentTitle.erase(std::remove(currentTitle.begin(), currentTitle.end(), '\"'), currentTitle.end());

            if (toLower(currentTitle) == searchTitle) {
                // Return the author part (before the first period)
                return line.substr(0, firstDot);
            }
        }
    }
    return ""; // Return empty string if no match
}

// Given a title and a list of MLA-style references, performs a case-
// insensitive search and extracts the name of the author corresponding to 
// any first match.
//
FastUtf8::Uniseries FetchAuthorByTitleUsingFastUtf8Uniseries(
                      uint8_t *puzTitle, uint8_t *puzReferences)
{
   FastUtf8::Uniseries sReferences(puzReferences);
   FastUtf8::Uniseries sTitle(puzTitle);
   FastUtf8::Uniseries sAuthor;
   uint8_t *puzAuthorFirst;
   uint8_t *puzAuthorLast = nullptr;

   // Prepare a wildcarded search string to match a line, within a list of 
   // MLA-style references, where the title matches "clock without hands", 
   // with wildcards in place of the author's last name and first name.
   FastUtf8::Uniseries sSearchPattern("\n*, *. ");
   sSearchPattern += puzTitle;

   // Prepare a set of tokens for slicing the author's name from the rest 
   // of the line.  There is only one token in this set.
   FastUtf8::Uniseries sTokenSet(".");

   // Get pointers to the first and last code points within the first title 
   // that matches the search pattern.
   puzAuthorFirst = sReferences.casepFindWild(sSearchPattern);

   if (puzAuthorFirst)
   {
      puzAuthorLast = sReferences.pFindToken(puzAuthorFirst, sTokenSet);
   }

   // Construct a Uniseries from the content between the pointers.
   if (puzAuthorLast && puzAuthorLast > puzAuthorFirst)
   {
      sAuthor.fromSlice(puzAuthorFirst, puzAuthorLast);
   }
   else
   {
      sAuthor = "No match found for ";
	  sAuthor += puzTitle;
   }

   return sAuthor;
}

// Invokes one of the above two MLA-title-extraction functions for ASCII text. 
// Invokes the FastUtf8-based function for a version of the same text in Greek 
// and in Georgian script.  Optionally reruns the functions a bunch of times to 
// capture and display performance outcomes.
//
int TimeAuthorByTitle(char *pszReferences, char *pszTitle, 
                       char *pszCodePointSet, int iReps, bool bUseStdString)
{
   const double fBase = 10.0;
   const double fExpNanoseconds = 9.0;
   const double fExpMilliseconds = 3.0;

   std::chrono::time_point<std::chrono::high_resolution_clock> timeStart;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeFinish;
   uint64_t uTime;            // Duration from std::chrono.
   double   fTime;            // Timing represented in nanoseconds.
   float    fTimeInSeconds;   // Timing represented in seconds.
   int      nReps = iReps;

   std::cout << "    From list of references..." << std::endl;
   std::cout << pszReferences << std::endl << std::endl;
   std::cout << "    ...and title..." << std::endl;
   std::cout << pszTitle << std::endl;

   if (bUseStdString)
   {
      // Get and display output using the function based on std::string.
      std::string strAuthor = FetchAuthorByTitleUsingStdString(
                      pszTitle, pszReferences);
      std::cout << std::endl << 
           "    ...extracted author: " << std::endl << strAuthor <<  std::endl;
      std::cout << "    ...using std::string." << std::endl << std::endl;

      // Rerun the std:string-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         strAuthor = FetchAuthorByTitleUsingStdString(
                      pszTitle, pszReferences);
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Represent the std:string-based function's timing in seconds, to 
      // millisecond precision.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "std::string (%s) demo time, with %d reps:\n     %.3f seconds\n\n", 
                      pszCodePointSet, iReps, fTimeInSeconds);
   }
   else
   {
      // Get and display output from the function based on FastUtf8::Uniseries.
      FastUtf8::Uniseries sAuthor = FetchAuthorByTitleUsingFastUtf8Uniseries(
                      reinterpret_cast<uint8_t *> (pszTitle), 
                      reinterpret_cast<uint8_t *> (pszReferences));

      std::cout << std::endl << 
           "    ...extracted author: " << std::endl << sAuthor << std::endl;
      std::cout << "    ...using FastUtf8::Uniseries." 
                      << std::endl << std::endl;

      // Rerun the FastUtf8::Uniseries-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         sAuthor = FetchAuthorByTitleUsingFastUtf8Uniseries(
                         reinterpret_cast<uint8_t *> (pszTitle), 
                         reinterpret_cast<uint8_t *> (pszReferences));
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Display the FastUtf8::Uniseries-based function's timing.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                         timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                         pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "FastUtf8::Uniseries (%s) demo time, with %d reps:\n     %.3f seconds\n\n", 
                         pszCodePointSet, iReps, fTimeInSeconds);
   }

   return 0;
}

// Drives display of content search and token-based separation functionality 
// of FastUtf8::Uniseries, and provides a performance comparison with 
// std::string.  Declares and initializes MLA-style lists of literary 
// references, in Latin text and in Greek and Georgian script.  Passes these, 
// along with one of the authors' lowercased last names, to a function that 
// gets output and timing results for MLA-title-extraction functions for 
// console display.
//
int FetchAuthorByTitle(int iReps)
{
   // This is a list of MLA-style literary references.
   char szReferencesAscii[900] = "\
Capote, Truman. Breakfast at Tiffany's: A Short Novel and Three Stories. Random House, 1958.\n\
Capote, Truman. In Cold Blood. Random House, 1965.\n\
Capote, Truman. Other Voices, Other Rooms. Random House, 1948.\n\
Hellman, Lillian. The Children's Hour. 1934. Famous American Plays of the 1930s, edited by Harold Clurman, Dell, 1959.\n\
Hellman, Lillian. Toys in the Attic: A New Play. Random House, 1960.\n\
McCullers, Carson. The Heart Is a Lonely Hunter. Houghton Mifflin, 1940.\n\
McCullers, Carson. The Member of the Wedding. Houghton Mifflin, 1946.\n\
McCullers, Carson. Clock Without Hands. Houghton Mifflin, 1961.\n\
Williams, Tennessee. The Glass Menagerie. Tennessee Williams: Plays 1937 through 1955, edited by Mel Gussow and Kenneth Holditch, Library of America, 2000, pp. 217-331.\n\
Williams, Tennessee. \"The Night of the Iguana.\" Three by Tennessee, edited by Darvin Kane, Signet, 1976, pp. 1-122.";
   char szTitleAscii[20] = "clock without hands";
   char szCodePointSetAscii[6] = "ASCII";

   // This is a Greek transliteration of the above references.
   char szReferencesGreek[2614] = "\
Καπότε, Τρούμαν. Πρωινό στο Tiffany's: Ένα σύντομο μυθιστόρημα και τρεις ιστορίες. Random House, 1958.\n\
Καπότε, Τρούμαν. Στο Ψυχρό Αίμα. Random House, 1965.\n\
Καπότε, Τρούμαν. Άλλες Φωνές, Άλλα Δωμάτια. Random House, 1948.\n\
Χέλμαν, Λίλιαν. Η Ώρα των Παιδιών. 1934. Διάσημα Αμερικανικά Θεατρικά Έργα της δεκαετίας του 1930, επιμέλεια Χάρολντ Κλούρμαν, Ντελ, 1959.\n\
Χέλμαν, Λίλιαν. Παιχνίδια στη Σοφίτα: Ένα Νέο Παιχνίδι. Random House, 1960.\n\
ΜακΚάλερς, Κάρσον. Η Καρδιά Είναι Ένας Μοναχικός Κυνηγός. Χάουτον Μίφλιν, 1940.\n\
ΜακΚάλερς, Κάρσον. Το Μέλος του Γάμου. Χάουτον Μίφλιν, 1946.\n\
ΜακΚάλερς, Κάρσον. Ρολόι χωρίς χέρια. Χάουτον Μίφλιν, 1961.\n\
Ουίλιαμς, Τενεσί. Το Γυάλινο Ζωολογικό Κήπο. Ουίλιαμς, Τενεσί: Θεατρικά έργα 1937 έως 1955, επιμέλεια Μελ Γκούσοου και Κένεθ Χόλντιτς, Βιβλιοθήκη της Αμερικής, 2000, pp. 217-331.\n\
Ουίλιαμς, Τενεσί. \"Η Νύχτα της Ιγκουάνα.\" Τρία από τον Τενεσί, επιμέλεια Ντάρβιν Κέιν, Σφραγιδόλιθος, 1976, pp. 1-122.";
   char szTitleGreek[35] = "Ρολόι χωρίς χέρια";
   char szCodePointSetGreek[6] = "Greek";

   // This translation of the references is mostly in Georgian. Some Latin 
   // letters with strokes are mixed in for case-insensitive matching.
   char szReferencesMixed[3585] = "\
კაპოტე, Ⱦრუმენი. საუზმე ტიფანისთან: მოკლე რომანი და სამი მოთხრობა. რენდომ ჰაუსი, 1958.\n\
კაპოტე, Ⱦრუმენი. ცივსისხლიანად. რენდომ ჰაუსი, 1965.\n\
კაპოტე, Ⱦრუმენი. სხვა ხმები, სხვა ოთახები. რენდომ ჰაუსი, 1948.\n\
ჰელმანი, ლილიანი. ბავშვთა საათი. 1934. 1930-იანი წლების ცნობილი ამერიკული პიესები, რედაქტორი ჰაროლდ კლურმანი, დელის, 1959.\n\
ჰელმანი, ლილიანი. სათამაშოები სხვენში: ახალი თამაში. რენდომ ჰაუსი, 1960.\n\
მȺკკალერსი, კȺრსონი. გული მარტოსული მონადირეა. ჰოტონ მიფლინი, 1940.\n\
მȺკკალერსი, კȺრსონი. ქორწილის წევრი. ჰოტონ მიფლინი, 1946.\n\
მȺკკალერსი, კȺრსონი. საათი ხელების გარეშე. ჰოტონ მიფლინი, 1961.\n\
უილიამსი, Ⱦენესი. შუშის ზოოპარკი. ტენესი უილიამსი: პიესები 1937 წლიდან 1955 წლამდე, რედაქტორები მელ გასოუ და კენეტ ჰოლდიჩი, ამერიკის ბიბლიოთეკა, 2000, გვ. 217-331.\n\
უილიამსი, Ⱦენესი. \"იგუანას ღამე.\" „სამი ტენესის მიერ“, რედაქტორი დარვინ კეინი, ხელმოწერა, 1976, გვ. 1-122.";
   char szTitleMixed[81] = "საათი ხელების გარეშე";
   char szCodePointSetMixed[15] = "mixed Georgian";

   // These calls pass the references and author last names to the functions 
   // that perform the search.  They also accumulate the associated timings 
   // for multiple quiet repetitions.  They display all results at the console.
   TimeAuthorByTitle(szReferencesAscii, szTitleAscii, szCodePointSetAscii, 
                      iReps, /* bUseStdString = */ true);
   TimeAuthorByTitle(szReferencesAscii, szTitleAscii, szCodePointSetAscii, 
                      iReps, /* bUseStdString = */ false);
   TimeAuthorByTitle(szReferencesGreek, szTitleGreek, szCodePointSetGreek, 
                      iReps, /* bUseStdString = */ false);
   TimeAuthorByTitle(szReferencesMixed, szTitleMixed, szCodePointSetMixed, 
                      iReps, /* bUseStdString = */ false);
   return 0;
}

// Demonstrates the static FastUtf8::Uniseries methods:
//
//   getLength()      Get content length in code points.
//   getSize()        Get content size in bytes.
//   getSizeFolded()  Get content size anticipated after case folding.
//   getFolded()      Get case-folded content.
//   is7Bit()         Is the current content all 7-bit ASCII characters?
//
// The static methods are provided for ease of access without requiring a 
// Uniseries instance.
//
int UniseriesStaticMethodsDemo(void)
{
   // Declare an ASCII string and a circled Latin series.
   char szBerryQuote[88] = 
    "I don't remember when I did not know Port William, the town and the neighborhood.";
   uint8_t uzCircledLatinQuote[353] = 
    "Ⓘ ⓓⓞⓝ’ⓣ ⓡⓔⓜⓔⓜⓑⓔⓡ ⓦⓗⓔⓝ Ⓘ ⓓⓘⓓ ⓝⓞⓣ ⓚⓝⓞⓦ Ⓟⓞⓡⓣ Ⓦⓘⓛⓛⓘⓐⓜ, ⓣⓗⓔ ⓣⓞⓦⓝ ⓐⓝⓓ ⓣⓗⓔ ⓝⓔⓘⓖⓗⓑⓞⓡⓗⓞⓞⓓ.";

   // Demonstrate methods that get the length and size of each.
   std::cout << "Length and size example:"  << std::endl;

   int     lenBerry = FastUtf8::Uniseries::getLength(szBerryQuote);
   int     lenCircled = FastUtf8::Uniseries::getLength(uzCircledLatinQuote);
   size_t  sizeBerry = FastUtf8::Uniseries::getSize(szBerryQuote);
   size_t  sizeCircled = FastUtf8::Uniseries::getSize(uzCircledLatinQuote);

   std::cout << "ASCII quote:"  << std::endl << szBerryQuote << std::endl;
   std::cout << "     Length: " << lenBerry << std::endl;
   std::cout << "      Bytes: " << sizeBerry << std::endl;
   std::cout << "In circled Latin:"  << std::endl << uzCircledLatinQuote << 
                   std::endl;
   std::cout << "     Length: " << lenCircled << std::endl;
   std::cout << "      Bytes: " << sizeCircled << std::endl << std::endl;

   // Allocate buffers sufficient for the case-folded ASCII and circled Latin 
   // content.
   size_t  sizeFoldedBerry = FastUtf8::Uniseries::getSizeFolded(szBerryQuote);
   size_t  sizeFoldedCircled = FastUtf8::Uniseries::getSizeFolded(
                   uzCircledLatinQuote);
   char    *pszFoldedBerry = 
                   reinterpret_cast<char *> (std::malloc(sizeFoldedBerry));
   uint8_t *puzFoldedCircled = 
                   reinterpret_cast<uint8_t *> (std::malloc(sizeFoldedCircled));

   // Place the case-folded ASCII and circled Latin content into the buffers.
   if (pszFoldedBerry && puzFoldedCircled)
   {
      Uniseries sFoldedBerry = FastUtf8::Uniseries::getFolded(szBerryQuote);
      Uniseries sFoldedCircled = FastUtf8::Uniseries::getFolded(
                   uzCircledLatinQuote);

      strncpy(pszFoldedBerry, 
              reinterpret_cast<char *> (sFoldedBerry.getContent()), 
              sizeFoldedBerry);
      strncpy(reinterpret_cast<char *> (puzFoldedCircled), 
              reinterpret_cast<char *> (sFoldedCircled.getContent()), 
              sizeFoldedCircled);

      // Show the case-folded content, and demonstrate 7-bit ASCII check.
      std::cout << "Case-folded ASCII quote:"  << std::endl << 
                   pszFoldedBerry << std::endl;

      if (FastUtf8::Uniseries::is7Bit(pszFoldedBerry))
      {
         std::cout << "     This is 7-bit ASCII text."  << std::endl;
      }
      else
      {
         std::cout << "     This is not 7-bit ASCII text."  << std::endl;
      }
      
      std::cout << std::endl << 
                   "Case-folded circled Latin quote:"  << std::endl << 
                   puzFoldedCircled << std::endl;

      if (FastUtf8::Uniseries::is7Bit(puzFoldedCircled))
      {
         std::cout << "     This is 7-bit ASCII text."  << std::endl;
      }
      else
      {
         std::cout << "     This is not 7-bit ASCII text."  << std::endl;
      }
      
      std::cout << std::endl;
      free(pszFoldedBerry);
      free(puzFoldedCircled);
   }
   
   return 0;
}

// Demonstrates this FastUtf8::Uniseries functionality for ASCII:
//
//   Fast one-call whole content case folding (lowercasing);
//   Case-insensitive whole content comparison;
//   Case-insensitive partial content comparison and find (returning an index);
//   Wildcard comparison, with / without case sensitivity;
//   Content separation over a buffer that remains in place (speedy!); and
//   Trimming of outboard white space.
//
int AsciiUniseriesMultiFuncDemo(void)
{
   // Declarations of multilingual variants of "Uniseries ASCII demo."
   Uniseries sDemo = "Uniseries ASCII demo";

   // Case-folding demo.
   std::cout << "Case-folding (lowercasing) example:"  << std::endl;

   // This first call is for UTF-8 compatibility.  Can use strlen() for ASCII, 
   // as an alternative.
   size_t sizeFolded = Uniseries::getSizeFolded(sDemo);
   Uniseries sDemoFolded1 = Uniseries::getFolded(sDemo, sizeFolded);
   Uniseries sDemoFolded2 = "uniseries ascii demo";

   if (sDemoFolded1 == sDemoFolded2)
   {
      std::cout << "      Mixed case ASCII: " << 
         sDemo << std::endl;
      std::cout << "     Case-folded ASCII: " << 
         sDemoFolded1 << std::endl;
   }

   std::cout << std::endl;

   // Demo of case-insensitive whole content comparison.
   std::cout << "Case-insensitive whole content comparison:"  << std::endl;

   if (sDemo.caseCompare(sDemoFolded1))
   {
      std::cout << "     " << sDemoFolded1 << "  matches  " << 
         sDemo << std::endl;
   }

   std::cout << std::endl;

   // Demo of case-insensitive partial content comparison.
   std::cout << "Case-insensitive partial content comparison:"  << std::endl;

   Uniseries sAscii1 = sDemo + ", added text including MiXeD cAsE words";

   sAscii1.setCaseInsensitive();

   if (sAscii1.contains("mixed case"))
   {
      std::cout << "     This content..." << std::endl;
      std::cout << "        " << sAscii1 << std::endl;
      std::cout << "     ...contains the words..." << std::endl;
	  std::cout << "       mixed case" << std::endl;
   }

   std::cout << std::endl;

   // Demo of case-sensitive and case-insensitive partial content lookup.
   std::cout << "Case-insensitive partial content lookup:"  << std::endl;
   Uniseries sAscii2 = "This ASCII demo, with more text, has yet more";
   Uniseries sAscii3 = "The words, in multiple lines, are space-separated ";
   Uniseries sAscii4 = "Commas, too, can be separator characters";
   Uniseries sAsciiCombo = sAscii1 + "\n" + sAscii2 + "\n" + sAscii3 + 
      "\n" + sAscii4;

   // When we call ::find() on a Uniseries object that's set up for case-
   // sensitive comparison, we won't find an all-lowercase portion unless 
   // there's an all-lowercase match.
   std::cout << "  -- Setting case sensitivity to true -- "  << std::endl;
   sAsciiCombo.setCaseSensitivity(true);

   int iCommas1 = sAsciiCombo.find(sAscii4);
   int iCommas2 = sAsciiCombo.find("commas");

   if (iCommas1 > 0)
   {
      std::cout << "     " << sAscii4 << "  has index  " << 
         iCommas1 << std::endl;
   }

   // Here, "Commas" fails to match "commas".
   if (iCommas2 > 0)
   {
      std::cout << "     " << "\"commas\"" << "  has index  " << 
         iCommas2 << std::endl;
   }
   else
   {
      std::cout << 
         "     Cannot find \"commas\"" << 
         std::endl;
   }

   // By switching case sensitivity off, we change the default behavior for 
   // the comparison methods including ::find().
   std::cout << "  -- Setting case sensitivity to false -- "  << std::endl;
   sAsciiCombo.setCaseSensitivity(false);

   // Now that we've made that change, "Commas" matches "commas".
   iCommas2 = sAsciiCombo.find("commas");

   if (iCommas2 > 0)
   {
      std::cout << "     " << "\"commas\"" << "  has index  " << 
         iCommas2 << std::endl;
   }
   else
   {
      std::cout << 
         "     Cannot find \"commas\"" << 
         std::endl;
   }

   std::cout << std::endl;

   // Matching wildcards demo.
   std::cout << "Matching wildcards:"  << std::endl;

   if (sAsciiCombo.caseCompareWild("*ascii DEMO? WITH more*"))
   {
      std::cout << 
         "     This content..." << std::endl << sAsciiCombo << std::endl;
      std::cout << 
         "     ...matches the wildcarded and inverse-cased sequence..." << 
         std::endl;
	  std::cout <<  "       *ascii DEMO? WITH more*" << std::endl;
   }

   std::cout << std::endl;

   // Demo of content separation and trimming.
   std::cout << "Content separation and trimming:"  << std::endl;

   // We'll extract "separated" from the four lines of text we've created.
   // First we duplicate the Uniseries object.  The pSeparate() calls modify 
   // the content by replacing separator tokens with null terminators.  The 
   // tokens are the code points (in this case, ASCII characters) passed to 
   // Uniseries::pSeparate().
   Uniseries sComboDup = sAsciiCombo;

   // Separate the content by '-' characters.  For this demo, we capture 
   // but ignore the first portion.  (The compiler may warn us about that.)
   // The pSeparate() method relies on std::make_unique<FastUtf8::Uniseries> 
   // to get the pointer that it returns.
   std::unique_ptr<FastUtf8::Uniseries> psComboPart1 = 
                      sComboDup.pSeparate("-");

   // Separate the second portion by either newline or space characters.
   std::unique_ptr<FastUtf8::Uniseries> psComboPart2 = 
                      sComboDup.pSeparate("\n", /* bTrim = */ true);

   if (*psComboPart2 == "separated")  // note: without the trailing space
   {
      std::cout << "     Extracted this trimmed content..." << std::endl;
      std::cout << "        " << *psComboPart2 << std::endl;
      std::cout << "     ... from this content..." << 
         std::endl << sAsciiCombo << std::endl;
      std::cout << "     ... via two Uniseries::pSeparate() calls" << std::endl;
   }

   std::cout << std::endl;

   // Another example.
   // We'll find a numeric sequence in text separated by spaces and lines.
   Uniseries s123 = "123";
   Uniseries sTwoSeparatorCombo = "abc def ghi\n123 456 789\nrst uvw xyz";

   // We duplicate the Uniseries object like we did previously.
   sComboDup = sTwoSeparatorCombo;

   // Separate the text by newline characters only, then separate the second 
   // portion by either newline or space characters.  The content buffers 
   // previously allocated for the reused objects get deallocated here.  The 
   // Uniseries objects otherwise remain allocated until they go out of scope.
   psComboPart1 = sComboDup.pSeparate("\n");
   psComboPart2 = sComboDup.pSeparate(" \n");

   if (*psComboPart2 == s123)
   {
      std::cout << "     Extracted this content..." << std::endl;
      std::cout << "        " << *psComboPart2 << std::endl;
      std::cout << "     ... from this content..." << 
         std::endl << sTwoSeparatorCombo << std::endl;
      std::cout << "     ... via two Uniseries::pSeparate() calls" << std::endl;
   }

   std::cout << std::endl;
   return 0;
}

// Demonstrates this FastUtf8::Uniseries functionality for UTF-8:
//
//   UTF-8 support;
//   Easy-to-use case folding;
//   Case-insensitive whole content comparison;
//   Case-insensitive partial content comparison and find (returning an index);
//   Wildcard comparison, with / without case sensitivity;
//   Content separation over a buffer that remains in place; and
//   Trimming of outboard white space;
//   Validations:
//     that content comprises 7-bit ASCII characters, or
//     that content comprises valid UTF-8 code points.
//
// This function demonstrates those aspects of FastUtf8.
//
int Utf8UniseriesMultiFuncDemo(void)
{
   // Declarations of multilingual variants of "This is a UTF-8 demo."
   Uniseries sAdlam = "𞤚𞤸𞤭𞤧 𞤭𞤧 𞤢 𞤓𞤚𞤊-𞥘 𞤣𞤫𞤥𞤮";
   Uniseries sAmharic = "ይህ የ UTF-8 ማሳያ ነው።";
   Uniseries sArmenian = "Սա UTF-8 դեմո է։";
   Uniseries sBangla = "এটি UTF-8 এর একটি ডেমো।";
   Uniseries sCantonese = "呢個系UTF-8嘅演示。";
   Uniseries sCherokee = "ᎯᎠ ᎤᏣᏔ-8 ᏗᎦᏙᎤᏍᏗ ᎠᏍᎦᏯ.";
   Uniseries sDeseret = "𐐜𐐮𐑅 𐐮𐑆 𐐩 UTF-8 𐐼𐐯𐑋𐐬.";
   Uniseries sEnglish = "This is a UTF-8 demo.";
   Uniseries sGreek = "Αυτό είναι ένα demo UTF-8.";
   Uniseries sHebrew = "זהו הדגמה של UTF-8.";
   Uniseries sHindi = "यह एक UTF-8 डेमो है।";
   Uniseries sInuktitut = "ᐅᓇ UTF-8 ᑕᑯᒃᓴᐅᑎᑕᐅᔪᖅ.";
   Uniseries sJapanese = "これはUTF-8のデモです。";
   Uniseries sKlingon = "   -8 .";
   Uniseries sNepali = "यो UTF-8 को डेमो हो।";
   Uniseries sOdia = "ଏହା UTF-8 ର ଏକ ଡେମୋ ।";
   Uniseries sRunic = "ᛏᚺᛁᛊ ᛁᛊ ᚨ ᚢᛏᚠ-ᚹ ᛞᛖᛗᛟ·";
   Uniseries sRussian = "Это демонстрация UTF-8.";
   Uniseries sPashto = "دا د UTF-8 یوه نمونه ده.";
   Uniseries sPersian = "این یک دمو از UTF-8 است.";
   Uniseries sTamil = "இது UTF-8 இன் டெமோ ஆகும்.";
   Uniseries sTigrinya = "እዚ ናይ UTF-8 ዲሞ እዩ።";
   Uniseries sTelugu = "นఇది UTF-8 యొక్క డెమో.";
   Uniseries sThai = "นี่คือการสาธิตของ UTF-8";
   Uniseries sUrdu = "یہ UTF-8 کا ایک ڈیمو ہے۔";

   // Case-folding demo.
   std::cout << "Case-folding examples:"  << std::endl;

   size_t sizeFolded = Uniseries::getSizeFolded(sAdlam);
   Uniseries sAdlamFolded1 = Uniseries::getFolded(sAdlam, sizeFolded);
   Uniseries sAdlamFolded2 = "𞤼𞤸𞤭𞤧 𞤭𞤧 𞤢 𞤵𞤼𞤬-𞥘 𞤣𞤫𞤥𞤮";

   if (sAdlamFolded1 == sAdlamFolded2)
   {
      std::cout << "      Mixed case Adlam script: " << 
         sAdlam << std::endl;
      std::cout << "     Case-folded Adlam script: " << 
         sAdlamFolded1 << std::endl;
   }

   sizeFolded = Uniseries::getSizeFolded(sEnglish);
   Uniseries sEnglishFolded1 = Uniseries::getFolded(sEnglish, sizeFolded);
   Uniseries sEnglishFolded2 = "this is a utf-8 demo.";

   if (sEnglishFolded1 == sEnglishFolded2)
   {
      std::cout << "      Mixed case English text: " << 
         sEnglish << std::endl;
      std::cout << "     Case-folded English text: " << 
         sEnglishFolded1 << std::endl;
   }

   sizeFolded = Uniseries::getSizeFolded(sGreek);
   Uniseries sGreekFolded1 = Uniseries::getFolded(sGreek, sizeFolded);
   Uniseries sGreekFolded2 = "αυτό είναι ένα demo utf-8.";

   if (sGreekFolded1 == sGreekFolded2)
   {
      std::cout << "      Mixed-case Greek stichos: " << 
         sGreek << std::endl;
      std::cout << "     Case-folded Greek stichos: " << 
         sGreekFolded1 << std::endl;
   }

   std::cout << std::endl;

   // Demo of case-insensitive whole content comparison.
   std::cout << "Case-insensitive whole content comparison:"  << std::endl;
   sEnglish.setCaseSensitivity(/* bCaseSensitive = */ false);
   sGreek.setCaseInsensitive();

   if (sAdlam.caseCompare(sAdlamFolded1))
   {
      std::cout << "     " << sAdlamFolded1 << "  matches  " << 
         sAdlam << std::endl;
   }

   if (sEnglishFolded1 == "this is a utf-8 demo.")
   {
      std::cout << "     " << sEnglishFolded1 << "  matches  " << 
         "This is a UTF-8 demo." << std::endl;
   }

   if (sGreekFolded1 == sGreek)
   {
      std::cout << "     " << sEnglishFolded1 << "  matches  " << 
         sEnglish << std::endl;
   }

   std::cout << std::endl;

   // Demo of case-insensitive partial content comparison.
   std::cout << "Case-insensitive partial content comparison:"  << std::endl;

   Uniseries sMulti1 = sHindi + ", " + sRussian + ", " + 
      sPashto + ", " + sPersian + ", " + sTamil + ", " + sTigrinya;

   sMulti1.setCaseInsensitive();

   if (sMulti1.contains("это демонстрация utf-8"))
   {
      std::cout << "     This content..." << std::endl;
      std::cout << "        " << sMulti1 << std::endl;
      std::cout << "     ...contains the Russian stroka..." << std::endl;
	  std::cout << "       это демонстрация utf-8" << std::endl;
   }

   std::cout << std::endl;

   // Demo of case-sensitive and case-insensitive partial content lookup.
   std::cout << "Case-insensitive partial content lookup:"  << std::endl;
   Uniseries sMulti2 = sAmharic + ", " + sBangla + ", " + 
      sCantonese + ", " + sCherokee + ", " + sDeseret + ", " + sHebrew;
   Uniseries sMulti3 = sRunic + ", " + sInuktitut + ", " + 
      sJapanese + ", " + sKlingon + ", " + sNepali + ", " + sOdia;
   Uniseries sMulti4 = sTelugu + ", " + sThai + ", " + sUrdu;
   Uniseries sMultiCombo = sMulti1 + "\n" + sMulti2 + "\n" + sMulti3 + 
      "\n" + sMulti4;

   std::cout << "  -- Setting case sensitivity to true -- "  << std::endl;
   sMultiCombo.setCaseSensitivity(true);

   int iOdiaLain = sMultiCombo.find(sOdia);
   int iBindrune = sMultiCombo.find("ᛁᛊ");

   if (iOdiaLain > 0)
   {
      std::cout << "     " << sOdia << "  has index  " << 
         iOdiaLain << std::endl;
   }

   if (iBindrune > 0)
   {
      std::cout << "     " << "ᛁᛊ" << "  has index  " << 
         iBindrune << std::endl;
   }

   int iRussianStroka = sMultiCombo.find("это демонстрация utf-8");

   if (iRussianStroka > 0)
   {
      std::cout << "     " << "это демонстрация utf-8" << "  has index  " << 
         iRussianStroka << std::endl;
   }
   else
   {
      std::cout << 
         "     Cannot find Russian stroka / Не могу найти русскую строку" << 
         std::endl;
   }

   std::cout << "  -- Setting case sensitivity to false -- "  << std::endl;
   sMultiCombo.setCaseSensitivity(false);
   iRussianStroka = sMultiCombo.find("это демонстрация utf-8");

   if (iRussianStroka > 0)
   {
      std::cout << "     " << "это демонстрация utf-8" << "  has index  " << 
         iRussianStroka << std::endl;
   }
   else
   {
      std::cout << 
         "     Cannot find Russian stroka / Не могу найти русскую строку" << 
         std::endl;
   }

   std::cout << std::endl;

   // Matching wildcards demo.
   std::cout << "Matching wildcards:"  << std::endl;

   if (sMulti1.caseCompareWild("*ДЕМОНСТРА?ИЯ utf-8*"))
   {
      std::cout << "     This content..." << std::endl;
      std::cout << "        " << sMulti1 << std::endl;
      std::cout << "     ...matches the wildcarded and inverse-cased Cyrillic / Latin sequence..." << std::endl;
	  std::cout <<  "       *ДЕМОНСТРА?ИЯ utf-8*" << std::endl;
   }

   std::cout << std::endl;

   // Demo of content separation and trimming.
   std::cout << "Content separation and trimming:"  << std::endl;

   Uniseries sMultiComboDup = sMultiCombo;
   std::unique_ptr<FastUtf8::Uniseries> psMultiComboPart1 = 
                      sMultiComboDup.pSeparate("\n");
   std::unique_ptr<FastUtf8::Uniseries> psMultiComboPart2 = 
                      sMultiComboDup.pSeparate(" \n", /* bTrim = */ true);

   if (sAmharic == *psMultiComboPart2)
   {
      std::cout << "     Extracted this content..." << std::endl;
      std::cout << "        " << *psMultiComboPart2 << std::endl;
      std::cout << "     ... from this content..." << 
         std::endl << sMultiCombo << std::endl;
      std::cout << "     ... via two Uniseries::pSeparate() calls" << std::endl;
   }

   std::cout << std::endl;

   // Demo of 7-bit character validation and of converting 8-bit ASCII to 
   // valid UTF-8.
   std::cout << "Validations:"  << std::endl;
   char sz8BitAscii[6] = "\x80\x81\x82\xA5\xEA"; 
   Uniseries sFormer8Bit = sz8BitAscii;

   if (sEnglish.is7Bit())
   {
      std::cout << "     This content...  " << std::endl;
      std::cout << "        " << sEnglish << std::endl;
      std::cout << "     ...is 7-bit ASCII text" << std::endl;
   }

   std::cout << std::endl;

   if (sFormer8Bit.validate())
   {
      std::cout << "     This 8-bit ASCII content...  " << std::endl;
#if defined(_WIN32)
SetConsoleOutputCP(437);
#endif
      std::cout << "        " << sz8BitAscii << std::endl;
#if defined(_WIN32)
   SetConsoleOutputCP(CP_UTF8);
#endif
      std::cout << "     ...has been converted to this UTF-8 content..." << std::endl;
      std::cout << "        " << sFormer8Bit << std::endl;
   }

   std::cout << std::endl;
   return 0;
}

// Entry point for demo.
//
int main(int argc, char **argv)
{
   int  iRepetitions;
   int  iPart = 0;
   bool bComparePerformance = false;

#if defined(_WIN32)
   SetConsoleOutputCP(CP_UTF8);
   SetConsoleCP(CP_UTF8);
#endif

   // Get performance comparison results against standard library ASCII 
   // string functions?
   if (argc > 1 && (argv[1][0] == 'w' || 
                    argv[1][0] == 'p' || 
                    argv[1][0] == 'c'))
   {
      bComparePerformance = true;

      // How many times to repeat tests, for function time accumulation?
      if (argc > 2)
      {
         iRepetitions = atoi(argv[2]);
      }
      else
      {
         iRepetitions = 1000000;
      }
   }   
   else
   {
      bComparePerformance = false;
      iRepetitions = 0;
   }

   // Demo of fundamental std::string operations.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "std::string demo (ASCII)" << std::endl << std::endl;
   AsciiStdStringDemo();

   // Demo of FastUtf8::Uniseries operations in place of std::string.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "FastUtf8::Uniseries demo (ASCII)" << std::endl << std::endl;
   AsciiUniseriesDemo();

   // Demo of performance timings compared with the std::string class.
   if (bComparePerformance)
   {
      ++iPart;
      std::cout << std::endl << "Part " << iPart << std::endl;
      std::cout << "Performance demo: Separate, concatenate, and slice" << 
         std::endl << std::endl;
      AsciiPerformanceDemo(iRepetitions);
   }

   // Demo of FastUtf8::Uniseries UTF-8 operations similar to std::string.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "FastUtf8::Uniseries demo (UTF-8)" << std::endl << std::endl;
   Utf8UniseriesDemo();

   // Demo of search for any of a set of tokens.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "FastUtf8::Uniseries.pFindToken() demo" << std::endl << std::endl;
   UniseriespFindTokenDemo();

   // Demo for FastUtf8::Uniseries iterator.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "FastUtf8::Uniseries iterator demo" << std::endl << std::endl;
   UniseriesIteratorDemo();

   // Demo of static FastUtf8::Uniseries methods.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "Static FastUtf8::Uniseries methods demo" << std::endl << std::endl;
   UniseriesStaticMethodsDemo();

   // Demo of functionality not provided with the std::string class, for ASCII.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << 
      "FastUtf8::Uniseries features beyond std::string demo (ASCII)" << 
      std::endl << std::endl;
   AsciiUniseriesMultiFuncDemo();

   // Demo of functionality not provided with the std::string class, for UTF-8.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << 
      "FastUtf8::Uniseries features beyond std::string demo (UTF-8)" << 
	  std::endl << std::endl;
   Utf8UniseriesMultiFuncDemo();

   // Demo of search through semistructured content.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;

   if (bComparePerformance)
   {
      std::cout << "Performance demo: Fetch titles by author" << 
         std::endl << std::endl;
   }
   else
   {
      std::cout << "Targeted search: Fetch titles by author" << 
         std::endl << std::endl;
   }

   FetchTitlesByAuthor(iRepetitions);

   // Demo of targeted wildcard search through semistructured content.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;

   if (bComparePerformance)
   {
      std::cout << "Performance demo: Fetch author by title" << 
         std::endl << std::endl;
   }
   else
   {
      std::cout << "Targeted wildcard search: Fetch author by title" << 
         std::endl << std::endl;
   }

   FetchAuthorByTitle(iRepetitions);
   return 0;
}