// C++ demo for UTF-8-ready routines.
//
// Certain functions in this file comprise machine-generated code and are 
// described as such in the relevant comments.  All other code in this file 
// is copyright 2026 Kirk J Krauss and is a Derivative Work based on material 
// that is copyright 2025 Kirk J Krauss and available at
//
//     https://developforperformance.com/MatchingWildcardsInGoSwiftAndCpp.html
// 
// Licensed under the Apache License, Version 2.0 (the "License"); you may not 
// use this file except in compliance with the License.  You may obtain a copy 
// of the License at
// 
//     https://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the 
// License for the specific language governing permissions and limitations 
// under the License.
//
#if !defined(__cplusplus)
#error "This is a demo program for the FastUtf8 C++ class."
#error "Testcases for the C-style functions in fastutf8.cpp are available."
#error "See testutf8.cpp and its documentation."
#endif

#if defined(_WIN32)
#include <windows.h>      // For SetConsoleOutputCP()
#endif  // _WIN32

#include <iostream>
#include <cstdio>
#include <cstring>
#include <string>
#include <cmath>
#include <chrono>
#include "fastutf8.h"
using namespace FastUtf8;

// The code within the following function, along with the "AI Overview" text, 
// was generated by Google on April 16, 2026, in response to the query:
//
//   std::string demo with concatenate, separate, substring, whole string 
//   comparison, and substring find operations
//
// AI Overview
// This C++ demo demonstrates fundamental std::string operations: 
// concatenation (+, append), substring extraction (substr), finding 
// substrings (find, npos), and comparison (==). std::string provides 
// efficient, high-level text manipulation, with find() returning the index 
// of the first occurrence or std::string::npos if not found.
//
int AsciiStdStringDemo(void)
{
   // 1. Creation and Concatenation
   std::string s1 = "Hello";
   std::string s2 = "World";
   // Using + operator
   std::string s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   // Using append()
   s3.append(" Welcome."); // "Hello, World! Welcome."

   std::cout << "Concatenated: " << s3 << std::endl;

   // 2. Substring (Position, Length)
   // Extract "World"
   std::string sub = s3.substr(7, 5);
   std::cout << "Substring: " << sub << std::endl;

   // 3. Substring Find
   size_t found = s3.find("Welcome");
   if (found != std::string::npos) {
       std::cout << "'Welcome' found at: " << found << std::endl;
   }

   // 4. Whole String Comparison
   std::string s4 = "Hello, World! Welcome.";
   if (s3 == s4) {
       std::cout << "Strings are equal." << std::endl;
   }

   // 5. Separate (Splitting by character)
   size_t commaPos = s3.find(',');
   if (commaPos != std::string::npos) {
       std::string firstPart = s3.substr(0, commaPos);
       std::string secondPart = s3.substr(commaPos + 2); // Skip ", "
       std::cout << "Separated: '" << firstPart << "' and '" << secondPart << "'" << std::endl;
   }

   return 0;
}

// The code within the following function is based on the above machine-
// generated code but is modified to work with the FastUtf8::Uniseries class 
// in the place of std::string.  Inline comments are modified accordingly.
//
int AsciiUniseriesDemo(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   std::cout << "Concatenated: " << s3 << std::endl;

   // 2. Substring (Position, Length)
   // Extract "World"
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);
   std::cout << "Substring: " << sub << std::endl;

   // 3. Substring Find
   int iFound = s3.find("Welcome");

   if (iFound != -1)
   {
      std::cout << "'Welcome' found at: " << iFound << std::endl;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 == s4)
   {
      std::cout << "Strings are equal." << std::endl;
   }

   // 5. Separate (Splitting by character)
   int iCommaPos = s3.find(',');

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "
      std::cout << "Separated: '" << sFirstPart << "' and '" << sSecondPart << "'" << std::endl;
   }

   return 0;
}

// This code is similar to the above AsciiUniseriesDemo() code but with 
// Japanese content.  To build it with the Microsoft compiler, use the /utf-8 
// switch for best content display.  The (N)SimSun or MS Gothic fonts include 
// the necessary ideographs.
//
int Utf8UniseriesDemo(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "こんにちは";
   Uniseries s2 = "は世界";
   // Using + operator
   Uniseries s3 = s1 + "、" + s2 + "！"; // "Hello, World!"
   s3 = s3 + " いらっしゃいませ。"; // "Hello, World! Welcome."

   std::cout << "Concatenated (連結済み)： " << s3 << std::endl;

   // 2. Substring (Position, Length)
   // Extract "World"
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 12);
   std::cout << "Substring (部分文字列)： " << sub << std::endl;

   // 3. Substring Find
   int iFound = s3.find("いらっしゃいませ");

   if (iFound != -1)
   {
      std::cout << "\"いらっしゃいませ\" found at (発見場所)： " << iFound << std::endl;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "こんにちは、は世界！ いらっしゃいませ。";

   if (s3 == s4)
   {
      std::cout << "Strings are equal (文字列は等しい)。" << std::endl;
   }

   // 5. Separate (Splitting by code point)
   int iCommaPos = s3.find("、");

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "
      std::cout << "Separated (分離済み)： \"" << sFirstPart << "\" and \"" << 
         sSecondPart << "\"" << std::endl;
   }

   return 0;
}

// This code is similar to the machine-generated std::string demo, but it 
// sends no output to the console.
int AsciiStdStringMute()
{
   // 1. Creation and Concatenation
   std::string s1 = "Hello";
   std::string s2 = "World";
   // Using + operator
   std::string s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   // Using append()
   s3.append(" Welcome."); // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World"
   std::string sub = s3.substr(7, 5);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   size_t found = s3.find("Welcome");

   if (found == std::string::npos)
   {
      return 1;
   }

   // 4. Whole String Comparison
   std::string s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   size_t commaPos = s3.find(',');
   if (commaPos != std::string::npos)
   {
      std::string firstPart = s3.substr(0, commaPos);
      std::string secondPart = s3.substr(commaPos + 2); // Skip ", "

      if (firstPart == secondPart)
      {
         return 1;
      }
   }

   return 0;
}

// This code is similar to the FastUtf8::Uniseries ASCII demo, but it sends no 
// output to the console.
int AsciiUniseriesMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   int iFound = s3.find("Welcome");

   if (iFound == -1)
   {
      return 1;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   int iCommaPos = s3.find(',');

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "

      if (sFirstPart == sSecondPart)
      {
         return 1;
      }
   }

   return 0;
}

// This is the same as the above function, except that it calls pSeparate() in 
// place of find().
int AsciiUniseriesSeparateMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   int iFound = s3.find("Welcome");

   if (iFound == -1)
   {
      return 1;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   std::unique_ptr<FastUtf8::Uniseries> psFirstPart = s3.pSeparate(',');

   if (*psFirstPart == s3)
   {
      return 1;   // "Hello" != " World! Welcome."
   }

   return 0;
}

// This is the same as the above function, except that it calls pFind() in 
// place of find().
int AsciiUniseriespFindMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "Hello";
   Uniseries s2 = "World";
   // Using + operator
   Uniseries s3 = s1 + ", " + s2 + "!"; // "Hello, World!"
   s3 = s3 + " Welcome."; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }

   // 3. Substring Find
   uint8_t *pFound = s3.pFind("Welcome");

   if (!pFound)
   {
      return 1;
   }

   // 4. Whole String Comparison
   Uniseries s4 = "Hello, World! Welcome.";

   if (s3 != s4)
   {
      return 1;
   }

   // 5. Separate (Splitting by character)
   uint8_t *pFirstPart = s3.pFind(',');

   if (!std::strcmp(
         reinterpret_cast<char *> (const_cast<uint8_t *> (pFirstPart)), 
         reinterpret_cast<char *> (const_cast<uint8_t *> (s3.getContent()))))
   {
      return 1;   // "Hello" != " World! Welcome."
   }

   return 0;
}

// This code is similar to the FastUtf8::Uniseries Japanese demo above, but it 
// sends no output to the console.
int Utf8UniseriesMute(void)
{
   // 1. Creation and Concatenation
   Uniseries s1 = "こんにちは";
   Uniseries s2 = "は世界";
   // Using + operator
   Uniseries s3 = s1 + "、" + s2 + "！"; // "Hello, World!"
   s3 = s3 + " いらっしゃいませ。"; // "Hello, World! Welcome."

   // 2. Substring (Position, Length)
   // Extract "World! Welcome."
   Uniseries sub = s3.slice(/* iFirst = */ 7, /* iLast = */ 22);

   if (sub == s1)
   {
      return 1;
   }
   
   // 3. Substring Find
   int iFound = s3.find("いらっしゃいませ");

   if (iFound == -1)
   {
      return 1;
   }
   
   // 4. Whole String Comparison
   Uniseries s4 = "こんにちは、は世界！ いらっしゃいませ。";

   if (s3 != s4)
   {
      return 1;
   }
   
   // 5. Separate (Splitting by code point)
   int iCommaPos = s3.find("、");

   if (iCommaPos != -1)
   {
      Uniseries sFirstPart = s3.slice(0, iCommaPos);
      Uniseries sSecondPart = s3.slice(iCommaPos + 2); // Skip ", "

      if (sFirstPart == sSecondPart)
      {
         return 1;
      }
   }
   
   return 0;
}

int AsciiPerformanceDemo(int iReps)
{
   const double fBase = 10.0;
   const double fExpNanoseconds = 9.0;
   const double fExpMilliseconds = 3.0;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeStart;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeFinish;
   uint64_t     uTime;
   double       fTime;
   float        fTimeInSeconds;
   int          nReps = iReps;

   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiStdStringMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "std::string (ASCII) demo, with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);
   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiUniseriesMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries ASCII muted demo, with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);
   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiUniseriesSeparateMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                         timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) / pow(fBase, fExpNanoseconds)) * 
                             pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries ASCII using pSeparate() in place of find(), with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);
   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (Utf8UniseriesMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) / pow(fBase, fExpNanoseconds)) * 
                      pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries UTF-8 demo, with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);

   nReps = iReps;
   timeStart = std::chrono::high_resolution_clock::now();

   while (nReps--)
   {
      if (AsciiUniseriespFindMute())
      {
         break;
      }
   }

   timeFinish = std::chrono::high_resolution_clock::now();
   uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();

   // Represent the timing in seconds, to millisecond precision.
   fTime = (static_cast<double> ((uTime) / pow(fBase, fExpNanoseconds)) * 
                      pow(fBase, fExpMilliseconds));
   fTimeInSeconds = (static_cast<float> (fTime / 1000));
   printf(
     "FastUtf8::Uniseries ASCII using pFind() in place of find(), with %d reps:\n     %.3f seconds\n", 
                      iReps, fTimeInSeconds);


   return 0;
}

// Entry point for demo.
//
int main(int argc, char **argv)
{
   int  iRepetitions;
   int  iPart = 0;
   bool bComparePerformance = false;

#if defined(_WIN32)
   SetConsoleOutputCP(CP_UTF8);
   SetConsoleCP(CP_UTF8);
#endif

   // Get performance comparison results against standard library ASCII 
   // string functions?
   if (argc > 1 && (argv[1][0] == 'w' || 
                    argv[1][0] == 'p' || 
                    argv[1][0] == 'c'))
   {
      bComparePerformance = true;

      // How many times to repeat tests, for function time accumulation?
      if (argc > 2)
      {
         iRepetitions = atoi(argv[2]);
      }
      else
      {
         iRepetitions = 1000000;
      }
   }   
   else
   {
      bComparePerformance = false;
      iRepetitions = 0;
   }

   // Demo of fundamental std::string operations.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "std::string demo (ASCII)" << std::endl << std::endl;
   AsciiStdStringDemo();

   // Demo of FastUtf8::Uniseries operations in place of std::string.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "FastUtf8::Uniseries demo (ASCII)" << std::endl << std::endl;
   AsciiUniseriesDemo();

   // Demo of performance timings compared with the std::string class.
   if (bComparePerformance)
   {
      ++iPart;
      std::cout << std::endl << "Part " << iPart << std::endl;
      std::cout << "Performance demo: Separate, concatenate, and slice" << 
         std::endl << std::endl;
      AsciiPerformanceDemo(iRepetitions);
   }

   // Demo of FastUtf8::Uniseries UTF-8 operations similar to std::string.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;
   std::cout << "FastUtf8::Uniseries demo (UTF-8)" << std::endl << std::endl;
   Utf8UniseriesDemo();
   return 0;
}