// C++ demo for UTF-8-ready routines.
//
// Certain functions in this file comprise machine-generated code and are 
// described as such in the relevant comments.  All other code in this file 
// is copyright 2026 Kirk J Krauss and is a Derivative Work based on material 
// that is copyright 2025 Kirk J Krauss and available at
//
//     https://developforperformance.com/MatchingWildcardsInGoSwiftAndCpp.html
// 
// Licensed under the Apache License, Version 2.0 (the "License"); you may not 
// use this file except in compliance with the License.  You may obtain a copy 
// of the License at
// 
//     https://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the 
// License for the specific language governing permissions and limitations 
// under the License.
//
#if !defined(__cplusplus)
#error "This is a demo program for the FastUtf8 C++ class."
#error "Testcases for the C-style functions in fastutf8.cpp are available."
#error "See testutf8.cpp and its documentation."
#endif

#if defined(_WIN32)
#include <windows.h>      // For SetConsoleOutputCP()
#endif  // _WIN32

#include <iostream>
#include <cstdio>
#include <cstring>
#include <string>
#include <cmath>
#include <chrono>
#include "fastutf8.h"
using namespace FastUtf8;

// Demonstration of parsing a buffer containing MLA references (author, title, 
// publisher, date).  Includes performance comparisons for two functions, one 
// based on std::string and generated in response to a Google query, and the 
// other based on FastUtf8::Uniseries.
//
#include <vector>
#include <sstream>
#include <algorithm>
#include <cctype>

// The code within the following two functions, along with the "AI Overview" 
// text, was generated by Google on May 2, 2026, in response to the query:
//
//   code a c++ function that accepts two buffers declared as char *, where 
//   one buffer comprises an author's last name, and the other buffer 
//   comprises a list of MLA references for individual authors, and where the 
//   function finds any first matching author among the references, so that 
//   for all list entries matching that author, the function creates a 
//   std::string comprising the author's first name, last name, and a list of 
//   titles among the MLA references, where the initial last name matching is 
//   case-insensitive
//
// AI Overview
// This C++ function processes two char* buffers—one containing a target last 
// name and the other a newline-separated list of MLA citations—to identify a 
// matching author, case-insensitively, and extracts their titles into a 
// formatted std::string. 
//
// Helper to make a string lowercase for case-insensitive comparison
std::string toLower(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c){ return std::tolower(c); });
    return s;
}

std::string FetchTitlesByAuthorUsingStdString(char* targetLastName, char* mlaReferences) {
    std::string targetName(targetLastName);
    std::string references(mlaReferences);
    std::string lowerTarget = toLower(targetName);
    
    std::stringstream ss(references);
    std::string line;
    std::string authorFullName = "";
    std::vector<std::string> titles;
    
    // Parse through references
    while (std::getline(ss, line)) {
        if (line.empty()) continue;

        // Simple MLA detection: "Lastname, Firstname." or similar
        size_t commaPos = line.find(',');
        if (commaPos != std::string::npos) {
            std::string lastName = line.substr(0, commaPos);
            
            // Case-insensitive match on last name
            if (toLower(lastName) == lowerTarget) {
                // Extract author full name on first match
                if (authorFullName.empty()) {
                    // Extract until the end of the first name, assuming "Last, First."
                    size_t periodPos = line.find('.', commaPos);
                    authorFullName = line.substr(0, periodPos + 1);
                }
                
                // Extract title (assuming it's after comma and inside italics or quotes)
                // This is a naive extraction focusing on MLA 8+ "Title."
                size_t firstPeriod = line.find('.');
                size_t secondPeriod = line.find('.', firstPeriod + 1);
                if (secondPeriod != std::string::npos) {
                    // Assume title is between first and second period
                    std::string title = line.substr(firstPeriod + 2, secondPeriod - (firstPeriod + 1));
                    titles.push_back(title);
                }
            }
        }
    }
    
    // Format output
    if (authorFullName.empty()) return "Author not found.";
    
    std::string result = "Author: " + authorFullName + "\nTitles:\n";
    for (const auto& title : titles) {
        result += "- " + title + "\n";
    }
    
    return result;
}

// Given an author's last name, performs a case-insensitive search and 
// extracts a list of titles corresponding to the full name for any first 
// match.
//
FastUtf8::Uniseries FetchTitlesByAuthorUsingFastUtf8Uniseries(
                      uint8_t *puzAuthorLastname, uint8_t *puzReferences)
{
   FastUtf8::Uniseries sReferences(puzReferences);
   FastUtf8::Uniseries sAuthorMatch(puzAuthorLastname);
   FastUtf8::Uniseries sTitles;
   uint8_t *puzTitle;

   // Search on the author's last name concatenated with comma. 
   // This ensures that (for example) "mccullers" won't match "mccullerson".
   sAuthorMatch += ",";
   uint8_t *puzFinding = sReferences.casepFind(sAuthorMatch);

   if (puzFinding)
   {
      // Got a match.  This call to pSeparate() places a null terminator 
	  // into the sReferences content buffer, in place of the "." that follows 
      // the author's full name, so that full name becomes a null-terminated 
	  // series of code points.
      uint8_t *puzAuthorName = sReferences.pSeparate(&puzFinding, ".");
	  FastUtf8::Uniseries sAuthorName(puzAuthorName);
	  sAuthorMatch = puzAuthorName;

      // This call to pSeparate() places a null terminator in place of the "." 
	  // that following the title (from the same line as the author's name).
	  // The bTrim flag elides any white space around the returned series.
      std::unique_ptr<FastUtf8::Uniseries> psAuthorSurname = 
                      sAuthorName.pSeparate(",", /* bTrim = */ true);

      // Piece together a heading line, such as "Titles by Carson McCullers:".
      sTitles = "Titles by";
      sTitles += sAuthorName;
      sTitles += " ";
      sTitles += *psAuthorSurname;

      // Piece together a title line, such as "- The Heart Is a Lonely Hunter."
      sTitles += ":\n- ";
      puzTitle = sReferences.pSeparate(&puzFinding, ".", /* bTrim = */ true);
      sTitles += puzTitle;
      sTitles += ".\n";

      do
      {
         // Search on the author's full name in the form that we've first 
		 // found it in the references.
         puzFinding = sReferences.casepFind(sAuthorMatch, puzFinding);

         if (!puzFinding)
         {
      	    break;  // No more matches.
         }

         // The next title should begin right after the next ". " sequence.
         puzFinding = sReferences.pFind(".", puzFinding);
         ++puzFinding;

         // This call to pSeparate() places a null terminator into the 
		 // sReferences content buffer, in place of the "." that follows the 
         // title.  The bTrim flag elides any white space around the title 
         // but does not affect the remaining sReferences content. 
         puzTitle = sReferences.pSeparate(&puzFinding, ".", /* bTrim = */ true);

         // Piece together a title line, such as "- Clock Without Hands.", 
		 // based on the null-terminated content, i.e., with minimal Uniseries 
		 // construction.
         sTitles += "- ";
         sTitles += puzTitle;
         sTitles += ".\n";
      } while (true);
   }
   else
   {
      sTitles = "No match found for ";
	  sTitles += puzAuthorLastname;
   }

   return sTitles;
}

// Invokes one of the above two MLA-title-extraction functions for ASCII text. 
// Invokes the FastUtf8-based function for a version of the same text in Greek 
// and in Georgian.  Optionally reruns the functions a bunch of times to 
// capture and display performance outcomes.
//
int TimeTitlesByAuthor(char *pszReferences, char *pszAuthorLastName, 
                       char *pszCodePointSet, int iReps, bool bUseStdString)
{
   const double fBase = 10.0;
   const double fExpNanoseconds = 9.0;
   const double fExpMilliseconds = 3.0;

   std::chrono::time_point<std::chrono::high_resolution_clock> timeStart;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeFinish;
   uint64_t uTime;          // Duration from std::chrono.
   double fTime;            // Timing represented in nanoseconds.
   float  fTimeInSeconds;   // Timing represented in seconds.
   int    nReps = iReps;

   std::cout << std::endl;
   std::cout << "    From list of references..." << std::endl;
   std::cout << pszReferences << std::endl << std::endl;

   if (bUseStdString)
   {
      // Get and display output using the function based on std::string.
      std::string strTitles = FetchTitlesByAuthorUsingStdString(
                      pszAuthorLastName, pszReferences);
      std::cout << std::endl << 
           "    ...extracted titles specified by author: " << 
                      pszAuthorLastName << "..." << std::endl;
      std::cout << strTitles  << "    ...using std::string." << 
                      std::endl << std::endl;

      // Rerun the std:string-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         strTitles = FetchTitlesByAuthorUsingStdString(
                      pszAuthorLastName, pszReferences);
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Represent the std:string-based function's timing in seconds, to 
      // millisecond precision.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "std::string (%s) demo time, with %d reps:\n     %.3f seconds\n", 
                      pszCodePointSet, iReps, fTimeInSeconds);
   }
   else
   {
      // Get and display output from the function based on FastUtf8::Uniseries.
      FastUtf8::Uniseries sTitles = FetchTitlesByAuthorUsingFastUtf8Uniseries(
                      reinterpret_cast<uint8_t *> (pszAuthorLastName), 
                      reinterpret_cast<uint8_t *> (pszReferences));

      std::cout << std::endl << 
           "    ...extracted titles specified by author: " << 
                   pszAuthorLastName << "..." << std::endl;
      std::cout << sTitles << "    ...using FastUtf8::Uniseries." 
                      << std::endl << std::endl;

      // Rerun the FastUtf8::Uniseries-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         sTitles = FetchTitlesByAuthorUsingFastUtf8Uniseries(
                         reinterpret_cast<uint8_t *> (pszAuthorLastName), 
                         reinterpret_cast<uint8_t *> (pszReferences));
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Display the FastUtf8::Uniseries-based function's timing.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                         timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                         pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "FastUtf8::Uniseries (%s) demo time, with %d reps:\n     %.3f seconds\n", 
                         pszCodePointSet, iReps, fTimeInSeconds);
   }

   return 0;
}

// Drives display of content search and token-based separation functionality 
// of FastUtf8::Uniseries, and provides a performance comparison with 
// std::string.  Declares and initializes MLA-style lists of literary 
// references, in Latin text and in Greek and Adlam script.  Passes these, 
// along with one of the authors' lowercased last names, to a function that 
// gets output and timing results for MLA-title-extraction functions for 
// console display.
//
int FetchTitlesByAuthor(int iReps)
{
   // This is a list of MLA-style literary references.
   char szReferencesAscii[900] = "\
Capote, Truman. Breakfast at Tiffany's: A Short Novel and Three Stories. Random House, 1958.\n\
Capote, Truman. In Cold Blood. Random House, 1965.\n\
Capote, Truman. Other Voices, Other Rooms. Random House, 1948.\n\
Hellman, Lillian. The Children's Hour. 1934. Famous American Plays of the 1930s, edited by Harold Clurman, Dell, 1959.\n\
Hellman, Lillian. Toys in the Attic: A New Play. Random House, 1960.\n\
McCullers, Carson. The Heart Is a Lonely Hunter. Houghton Mifflin, 1940.\n\
McCullers, Carson. The Member of the Wedding. Houghton Mifflin, 1946.\n\
McCullers, Carson. Clock Without Hands. Houghton Mifflin, 1961.\n\
Williams, Tennessee. The Glass Menagerie. Tennessee Williams: Plays 1937 through 1955, edited by Mel Gussow and Kenneth Holditch, Library of America, 2000, pp. 217-331.\n\
Williams, Tennessee. \"The Night of the Iguana.\" Three by Tennessee, edited by Darvin Kane, Signet, 1976, pp. 1-122.";
   char szAuthorLastnameAscii[10] = "mccullers";
   char szCodePointSetAscii[6] = "ASCII";

   // This is a Greek transliteration of the above references.
   char szReferencesGreek[2614] = "\
Καπότε, Τρούμαν. Πρωινό στο Tiffany's: Ένα σύντομο μυθιστόρημα και τρεις ιστορίες. Random House, 1958.\n\
Καπότε, Τρούμαν. Στο Ψυχρό Αίμα. Random House, 1965.\n\
Καπότε, Τρούμαν. Άλλες Φωνές, Άλλα Δωμάτια. Random House, 1948.\n\
Χέλμαν, Λίλιαν. Η Ώρα των Παιδιών. 1934. Διάσημα Αμερικανικά Θεατρικά Έργα της δεκαετίας του 1930, επιμέλεια Χάρολντ Κλούρμαν, Ντελ, 1959.\n\
Χέλμαν, Λίλιαν. Παιχνίδια στη Σοφίτα: Ένα Νέο Παιχνίδι. Random House, 1960.\n\
ΜακΚάλερς, Κάρσον. Η Καρδιά Είναι Ένας Μοναχικός Κυνηγός. Χάουτον Μίφλιν, 1940.\n\
ΜακΚάλερς, Κάρσον. Το Μέλος του Γάμου. Χάουτον Μίφλιν, 1946.\n\
ΜακΚάλερς, Κάρσον. Ρολόι χωρίς χέρια. Χάουτον Μίφλιν, 1961.\n\
Ουίλιαμς, Τενεσί. Το Γυάλινο Ζωολογικό Κήπο. Ουίλιαμς, Τενεσί: Θεατρικά έργα 1937 έως 1955, επιμέλεια Μελ Γκούσοου και Κένεθ Χόλντιτς, Βιβλιοθήκη της Αμερικής, 2000, pp. 217-331.\n\
Ουίλιαμς, Τενεσί. \"Η Νύχτα της Ιγκουάνα.\" Τρία από τον Τενεσί, επιμέλεια Ντάρβιν Κέιν, Σφραγιδόλιθος, 1976, pp. 1-122.";
   char szAuthorLastnameGreek[28] = "μακκάλερς";
   char szCodePointSetGreek[6] = "Greek";

   // This translation of the references is mostly in Georgian. Some Latin 
   // letters with strokes are mixed in for case-insensitive matching.
   char szReferencesMixed[3585] = "\
კაპოტე, Ⱦრუმენი. საუზმე ტიფანისთან: მოკლე რომანი და სამი მოთხრობა. რენდომ ჰაუსი, 1958.\n\
კაპოტე, Ⱦრუმენი. ცივსისხლიანად. რენდომ ჰაუსი, 1965.\n\
კაპოტე, Ⱦრუმენი. სხვა ხმები, სხვა ოთახები. რენდომ ჰაუსი, 1948.\n\
ჰელმანი, ლილიანი. ბავშვთა საათი. 1934. 1930-იანი წლების ცნობილი ამერიკული პიესები, რედაქტორი ჰაროლდ კლურმანი, დელის, 1959.\n\
ჰელმანი, ლილიანი. სათამაშოები სხვენში: ახალი თამაში. რენდომ ჰაუსი, 1960.\n\
მȺკკალერსი, კȺრსონი. გული მარტოსული მონადირეა. ჰოტონ მიფლინი, 1940.\n\
მȺკკალერსი, კȺრსონი. ქორწილის წევრი. ჰოტონ მიფლინი, 1946.\n\
მȺკკალერსი, კȺრსონი. საათი ხელების გარეშე. ჰოტონ მიფლინი, 1961.\n\
უილიამსი, Ⱦენესი. შუშის ზოოპარკი. ტენესი უილიამსი: პიესები 1937 წლიდან 1955 წლამდე, რედაქტორები მელ გასოუ და კენეტ ჰოლდიჩი, ამერიკის ბიბლიოთეკა, 2000, გვ. 217-331.\n\
უილიამსი, Ⱦენესი. \"იგუანას ღამე.\" „სამი ტენესის მიერ“, რედაქტორი დარვინ კეინი, ხელმოწერა, 1976, გვ. 1-122.";
   char szAuthorLastnameMixed[41] = "მⱥკკალერსი";
   char szCodePointSetMixed[15] = "mixed Georgian";

   // These calls pass the references and author last names to the functions 
   // that perform the search.  They also accumulate the associated timings 
   // for multiple quiet repetitions.  They display all results at the console.
   TimeTitlesByAuthor(szReferencesAscii, szAuthorLastnameAscii, 
                      szCodePointSetAscii, iReps, /* bUseStdString = */ true);
   TimeTitlesByAuthor(szReferencesAscii, szAuthorLastnameAscii, 
                      szCodePointSetAscii, iReps, /* bUseStdString = */ false);
   TimeTitlesByAuthor(szReferencesGreek, szAuthorLastnameGreek, 
                      szCodePointSetGreek, iReps, /* bUseStdString = */ false);
   TimeTitlesByAuthor(szReferencesMixed, szAuthorLastnameMixed, 
                      szCodePointSetMixed, iReps, /* bUseStdString = */ false);
   return 0;
}

// The code within the following two functions, along with the "AI Overview" 
// text, was generated by Google on May 7, 2026, in response to the query:
//
//   code a c++ function that accepts two buffers declared as char *, where 
//   one buffer comprises a title, and the other buffer comprises a list of 
//   MLA references for individual authors, and where the function finds any 
//   first matching title among the references, so that for a first list entry 
//   matching that title, the function creates a std::string comprising the 
//   author's name, where the initial title matching is case-insensitive
//
// AI Overview
// This C++ function searches for a case-insensitive title match within a 
// newline-separated list of MLA references. It uses std::string for robust 
// text handling, converting both the search title and references to lowercase 
// using std::tolower for comparison, then extracts the author name.

#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>
#include <cctype>

// Function to find author by title (case-insensitive)
std::string FetchAuthorByTitleUsingStdString(char* targetTitle, char* mlaReferences) {
    if (!targetTitle || !mlaReferences) return "";

    std::string searchTitle = toLower(std::string(targetTitle));
    std::string references(mlaReferences);
    std::stringstream ss(references);
    std::string line;

    // Process each reference entry line-by-line
    while (std::getline(ss, line)) {
        if (line.empty()) continue;

        // Assumes MLA format: Author(s). "Title." Journal...
        // Extract title part (assuming it's between first and second '.')
        size_t firstDot = line.find('.');
        size_t secondDot = line.find('.', firstDot + 1);
        
        if (firstDot != std::string::npos && secondDot != std::string::npos) {
            std::string currentTitle = line.substr(firstDot + 2, secondDot - firstDot - 2);
            
            // Remove leading/trailing quotes if necessary
            currentTitle.erase(std::remove(currentTitle.begin(), currentTitle.end(), '\"'), currentTitle.end());

            if (toLower(currentTitle) == searchTitle) {
                // Return the author part (before the first period)
                return line.substr(0, firstDot);
            }
        }
    }
    return ""; // Return empty string if no match
}

// Given a title and a list of MLA-style references, performs a case-
// insensitive search and extracts the name of the author corresponding to 
// any first match.
//
FastUtf8::Uniseries FetchAuthorByTitleUsingFastUtf8Uniseries(
                      uint8_t *puzTitle, uint8_t *puzReferences)
{
   FastUtf8::Uniseries sReferences(puzReferences);
   FastUtf8::Uniseries sTitle(puzTitle);
   FastUtf8::Uniseries sAuthor;
   uint8_t *puzAuthorFirst;
   uint8_t *puzAuthorLast = nullptr;

   // Prepare a wildcarded search string to match a line, within a list of 
   // MLA-style references, where the title matches "clock without hands", 
   // with wildcards in place of the author's last name and first name.
   FastUtf8::Uniseries sSearchPattern("\n*, *. ");
   sSearchPattern += puzTitle;

   // Prepare a set of tokens for slicing the author's name from the rest 
   // of the line.  There is only one token in this set.
   FastUtf8::Uniseries sTokenSet(".");

   // Get pointers to the first and last code points within the first title 
   // that matches the search pattern.
   puzAuthorFirst = sReferences.casepFindWild(sSearchPattern);

   if (puzAuthorFirst)
   {
      puzAuthorLast = sReferences.pFindToken(puzAuthorFirst, sTokenSet);
   }

   // Construct a Uniseries from the content between the pointers.
   if (puzAuthorLast && puzAuthorLast > puzAuthorFirst)
   {
      sAuthor.fromSlice(puzAuthorFirst, puzAuthorLast);
   }
   else
   {
      sAuthor = "No match found for ";
	  sAuthor += puzTitle;
   }

   return sAuthor;
}

// Invokes one of the above two MLA-title-extraction functions for ASCII text. 
// Invokes the FastUtf8-based function for a version of the same text in Greek 
// and in Georgian script.  Optionally reruns the functions a bunch of times to 
// capture and display performance outcomes.
//
int TimeAuthorByTitle(char *pszReferences, char *pszTitle, 
                       char *pszCodePointSet, int iReps, bool bUseStdString)
{
   const double fBase = 10.0;
   const double fExpNanoseconds = 9.0;
   const double fExpMilliseconds = 3.0;

   std::chrono::time_point<std::chrono::high_resolution_clock> timeStart;
   std::chrono::time_point<std::chrono::high_resolution_clock> timeFinish;
   uint64_t uTime;            // Duration from std::chrono.
   double   fTime;            // Timing represented in nanoseconds.
   float    fTimeInSeconds;   // Timing represented in seconds.
   int      nReps = iReps;

   std::cout << "    From list of references..." << std::endl;
   std::cout << pszReferences << std::endl << std::endl;
   std::cout << "    ...and title..." << std::endl;
   std::cout << pszTitle << std::endl;

   if (bUseStdString)
   {
      // Get and display output using the function based on std::string.
      std::string strAuthor = FetchAuthorByTitleUsingStdString(
                      pszTitle, pszReferences);
      std::cout << std::endl << 
           "    ...extracted author: " << std::endl << strAuthor <<  std::endl;
      std::cout << "    ...using std::string." << std::endl << std::endl;

      // Rerun the std:string-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         strAuthor = FetchAuthorByTitleUsingStdString(
                      pszTitle, pszReferences);
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Represent the std:string-based function's timing in seconds, to 
      // millisecond precision.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                      timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                      pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "std::string (%s) demo time, with %d reps:\n     %.3f seconds\n\n", 
                      pszCodePointSet, iReps, fTimeInSeconds);
   }
   else
   {
      // Get and display output from the function based on FastUtf8::Uniseries.
      FastUtf8::Uniseries sAuthor = FetchAuthorByTitleUsingFastUtf8Uniseries(
                      reinterpret_cast<uint8_t *> (pszTitle), 
                      reinterpret_cast<uint8_t *> (pszReferences));

      std::cout << std::endl << 
           "    ...extracted author: " << std::endl << sAuthor << std::endl;
      std::cout << "    ...using FastUtf8::Uniseries." 
                      << std::endl << std::endl;

      // Rerun the FastUtf8::Uniseries-based function a bunch of times, quietly.
      timeStart = std::chrono::high_resolution_clock::now();

      while (nReps--)
      {
         sAuthor = FetchAuthorByTitleUsingFastUtf8Uniseries(
                         reinterpret_cast<uint8_t *> (pszTitle), 
                         reinterpret_cast<uint8_t *> (pszReferences));
      }

      timeFinish = std::chrono::high_resolution_clock::now();

      // Display the FastUtf8::Uniseries-based function's timing.
      uTime = (std::chrono::duration_cast<std::chrono::nanoseconds>(
                         timeFinish - timeStart)).count();
      fTime = (static_cast<double> ((uTime) /
                         pow(fBase, fExpNanoseconds)) * pow(fBase, fExpMilliseconds));
      fTimeInSeconds = static_cast<float> (fTime / 1000);
      printf(
        "FastUtf8::Uniseries (%s) demo time, with %d reps:\n     %.3f seconds\n\n", 
                         pszCodePointSet, iReps, fTimeInSeconds);
   }

   return 0;
}

// Drives display of content search and token-based separation functionality 
// of FastUtf8::Uniseries, and provides a performance comparison with 
// std::string.  Declares and initializes MLA-style lists of literary 
// references, in Latin text and in Greek and Georgian script.  Passes these, 
// along with one of the authors' lowercased last names, to a function that 
// gets output and timing results for MLA-title-extraction functions for 
// console display.
//
int FetchAuthorByTitle(int iReps)
{
   // This is a list of MLA-style literary references.
   char szReferencesAscii[900] = "\
Capote, Truman. Breakfast at Tiffany's: A Short Novel and Three Stories. Random House, 1958.\n\
Capote, Truman. In Cold Blood. Random House, 1965.\n\
Capote, Truman. Other Voices, Other Rooms. Random House, 1948.\n\
Hellman, Lillian. The Children's Hour. 1934. Famous American Plays of the 1930s, edited by Harold Clurman, Dell, 1959.\n\
Hellman, Lillian. Toys in the Attic: A New Play. Random House, 1960.\n\
McCullers, Carson. The Heart Is a Lonely Hunter. Houghton Mifflin, 1940.\n\
McCullers, Carson. The Member of the Wedding. Houghton Mifflin, 1946.\n\
McCullers, Carson. Clock Without Hands. Houghton Mifflin, 1961.\n\
Williams, Tennessee. The Glass Menagerie. Tennessee Williams: Plays 1937 through 1955, edited by Mel Gussow and Kenneth Holditch, Library of America, 2000, pp. 217-331.\n\
Williams, Tennessee. \"The Night of the Iguana.\" Three by Tennessee, edited by Darvin Kane, Signet, 1976, pp. 1-122.";
   char szTitleAscii[20] = "clock without hands";
   char szCodePointSetAscii[6] = "ASCII";

   // This is a Greek transliteration of the above references.
   char szReferencesGreek[2614] = "\
Καπότε, Τρούμαν. Πρωινό στο Tiffany's: Ένα σύντομο μυθιστόρημα και τρεις ιστορίες. Random House, 1958.\n\
Καπότε, Τρούμαν. Στο Ψυχρό Αίμα. Random House, 1965.\n\
Καπότε, Τρούμαν. Άλλες Φωνές, Άλλα Δωμάτια. Random House, 1948.\n\
Χέλμαν, Λίλιαν. Η Ώρα των Παιδιών. 1934. Διάσημα Αμερικανικά Θεατρικά Έργα της δεκαετίας του 1930, επιμέλεια Χάρολντ Κλούρμαν, Ντελ, 1959.\n\
Χέλμαν, Λίλιαν. Παιχνίδια στη Σοφίτα: Ένα Νέο Παιχνίδι. Random House, 1960.\n\
ΜακΚάλερς, Κάρσον. Η Καρδιά Είναι Ένας Μοναχικός Κυνηγός. Χάουτον Μίφλιν, 1940.\n\
ΜακΚάλερς, Κάρσον. Το Μέλος του Γάμου. Χάουτον Μίφλιν, 1946.\n\
ΜακΚάλερς, Κάρσον. Ρολόι χωρίς χέρια. Χάουτον Μίφλιν, 1961.\n\
Ουίλιαμς, Τενεσί. Το Γυάλινο Ζωολογικό Κήπο. Ουίλιαμς, Τενεσί: Θεατρικά έργα 1937 έως 1955, επιμέλεια Μελ Γκούσοου και Κένεθ Χόλντιτς, Βιβλιοθήκη της Αμερικής, 2000, pp. 217-331.\n\
Ουίλιαμς, Τενεσί. \"Η Νύχτα της Ιγκουάνα.\" Τρία από τον Τενεσί, επιμέλεια Ντάρβιν Κέιν, Σφραγιδόλιθος, 1976, pp. 1-122.";
   char szTitleGreek[35] = "Ρολόι χωρίς χέρια";
   char szCodePointSetGreek[6] = "Greek";

   // This translation of the references is mostly in Georgian. Some Latin 
   // letters with strokes are mixed in for case-insensitive matching.
   char szReferencesMixed[3585] = "\
კაპოტე, Ⱦრუმენი. საუზმე ტიფანისთან: მოკლე რომანი და სამი მოთხრობა. რენდომ ჰაუსი, 1958.\n\
კაპოტე, Ⱦრუმენი. ცივსისხლიანად. რენდომ ჰაუსი, 1965.\n\
კაპოტე, Ⱦრუმენი. სხვა ხმები, სხვა ოთახები. რენდომ ჰაუსი, 1948.\n\
ჰელმანი, ლილიანი. ბავშვთა საათი. 1934. 1930-იანი წლების ცნობილი ამერიკული პიესები, რედაქტორი ჰაროლდ კლურმანი, დელის, 1959.\n\
ჰელმანი, ლილიანი. სათამაშოები სხვენში: ახალი თამაში. რენდომ ჰაუსი, 1960.\n\
მȺკკალერსი, კȺრსონი. გული მარტოსული მონადირეა. ჰოტონ მიფლინი, 1940.\n\
მȺკკალერსი, კȺრსონი. ქორწილის წევრი. ჰოტონ მიფლინი, 1946.\n\
მȺკკალერსი, კȺრსონი. საათი ხელების გარეშე. ჰოტონ მიფლინი, 1961.\n\
უილიამსი, Ⱦენესი. შუშის ზოოპარკი. ტენესი უილიამსი: პიესები 1937 წლიდან 1955 წლამდე, რედაქტორები მელ გასოუ და კენეტ ჰოლდიჩი, ამერიკის ბიბლიოთეკა, 2000, გვ. 217-331.\n\
უილიამსი, Ⱦენესი. \"იგუანას ღამე.\" „სამი ტენესის მიერ“, რედაქტორი დარვინ კეინი, ხელმოწერა, 1976, გვ. 1-122.";
   char szTitleMixed[81] = "საათი ხელების გარეშე";
   char szCodePointSetMixed[15] = "mixed Georgian";

   // These calls pass the references and author last names to the functions 
   // that perform the search.  They also accumulate the associated timings 
   // for multiple quiet repetitions.  They display all results at the console.
   TimeAuthorByTitle(szReferencesAscii, szTitleAscii, szCodePointSetAscii, 
                      iReps, /* bUseStdString = */ true);
   TimeAuthorByTitle(szReferencesAscii, szTitleAscii, szCodePointSetAscii, 
                      iReps, /* bUseStdString = */ false);
   TimeAuthorByTitle(szReferencesGreek, szTitleGreek, szCodePointSetGreek, 
                      iReps, /* bUseStdString = */ false);
   TimeAuthorByTitle(szReferencesMixed, szTitleMixed, szCodePointSetMixed, 
                      iReps, /* bUseStdString = */ false);
   return 0;
}

// Entry point for demo.
//
int main(int argc, char **argv)
{
   int  iRepetitions;
   int  iPart = 0;
   bool bComparePerformance = false;

#if defined(_WIN32)
   SetConsoleOutputCP(CP_UTF8);
   SetConsoleCP(CP_UTF8);
#endif

   // Get performance comparison results against standard string methods? 
   if (argc > 1 && (argv[1][0] == 'w' || 
                    argv[1][0] == 'p' || 
                    argv[1][0] == 'c'))
   {
      bComparePerformance = true;

      // How many times to repeat tests, for function time accumulation?
      if (argc > 2)
      {
         iRepetitions = atoi(argv[2]);
      }
      else
      {
         iRepetitions = 1000000;
      }
   }   
   else
   {
      bComparePerformance = false;
      iRepetitions = 0;
   }

   // Demo of search through semistructured content.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;

   if (bComparePerformance)
   {
      std::cout << "Performance demo: Fetch titles by author" << 
         std::endl << std::endl;
   }
   else
   {
      std::cout << "Targeted search: Fetch titles by author" << 
         std::endl << std::endl;
   }

   FetchTitlesByAuthor(iRepetitions);

   // Demo of targeted wildcard search through semistructured content.
   ++iPart;
   std::cout << std::endl << "Part " << iPart << std::endl;

   if (bComparePerformance)
   {
      std::cout << "Performance demo: Fetch author by title" << 
         std::endl << std::endl;
   }
   else
   {
      std::cout << "Targeted wildcard search: Fetch author by title" << 
         std::endl << std::endl;
   }

   FetchAuthorByTitle(iRepetitions);
   return 0;
}